module.exports = {
    nowrapper:{
        description:"A wrapper element is the parent container that surrounds a component's internal elements, providing structural layout, styling, positioning, spacing, and interaction behavior. It serves as the root element through which styles, attributes, event handlers, and accessibility properties can be applied consistently across the component.",
        type:"boolean",
        dvalue:false
    },
    dsTheme:{
        type:'predefined',
        description:"Design System Theme Configuration is a centralized set of design tokens, styles, and visual properties that define the appearance and behavior of UI components across an application. It enables consistent customization of attributes such as colors, typography, spacing, sizing, borders, shadows, and states, ensuring a unified look and feel while supporting theming, branding, and accessibility requirements.",
        ___:{
            predefined:{
                from:'statics',
                mapping:'ds.preset',
                overwirte:{
                    outer:{
                        type:'enum',
                        ___:{
                            enum:{
                                from:'statics',
                                mapping:'global.spaces',
                            }
                        }
                    }
                }
            }
        }
    },
    config:{
        description:"The configuration supports design system–driven customization across various elements, including the avatar image, wrapper, and initials. Properties such as size, shape, border, background color, and typography can be configured through the design system, ensuring visual consistency, accessibility, and alignment with application design standards across different themes and use cases.",
        type:"nested",
        ___:{
            nested:{   
                wrapper:{
                    dvalue:{},
                    type:'predefined',
                    description:"Default button",
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                content:null,
                            }
                        }
                    }
                },
                initial:{
                    type:'predefined',
                    description:"Default button",
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                content:null,
                                ds:{
                                    type:'nested',
                                    ___:{
                                        nested:{
                                            css:{
                                                type:'nested',
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            type:'nested',
                                                            ___:{
                                                                nested:{
                                                                    family:{
                                                                        dvalue:'md'
                                                                    },
                                                                    fontsize:{
                                                                        dvalue:'sm'
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    initial:{
        type:"nested",
        description:'Initial Text Content is a text-based fallback representation used when an image or avatar is unavailable. The component accepts a user first name and last name as input and automatically generates initials by extracting the first character from each name. For example, "John Doe" is displayed as "JD", and "Priya Sharma" is displayed as "PS"',
        ___:{
            nested:{
                size:{
                    type:'enum',
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:'global.font.size',
                        }
                    }
                },
                family:{
                    type:'enum',
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:'global.font.family',
                        }
                    }
                },
                display:{
                    type:'boolean',
                    dvalue:false
                },
                value:{
                    type:'string'
                },
                fallback:{
                    type:'string'
                }
            }
        }
    },
}