const schema = {
    "type":true,
    "name":true,
    "mapId":true,
    "hashId":true,
    "nameHash":true,
    "description":true,
    "roleMapping":true,
    "actions.fetch":true,
    "actions.update":true,
    "actions.create":true,
    "actions.remove":true,
    "roleMappingHash":true
}

const update = () => {
    return {...schema, ...{hashId:false, mapId:false}}
}

module.exports = {
    response:{
        exclude:{
            enable:true,
            kies:{
                ts:true,
                nameHash:true,
                roleMappingHash:true
            }
        },
    },
    valuemap: {},

    md5Hash:{
        hashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"number",
                    from:"random"
                }
            }
        },
        nameHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"name",
                    from:"body-item"
                }
            }
        },
        roleMappingHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"type",
                    from:"body-item"
                },
                3:{
                    map:"roleMapping",
                    from:"body-item"
                },
                /*--4:{
                    map:"actions.fetch",
                    from:"body-item"
                },
                5:{
                    map:"actions.update",
                    from:"body-item"
                },
                6:{
                    map:"actions.insert",
                    from:"body-item"
                },
                7:{
                    map:"actions.remove",
                    from:"body-item"
                }--*/
            }
        }
    },

    schema:{
        default:schema,
        update:update()
    },

    signature:{
        merge:{
            enable:true
        },
        creation:{
            enable:true,
            nodes:{
                _id:{
                    enable:true,
                    valueType:"objectId"
                },
                _merchantId:{
                    enable:true,
                    valueType:"objectId"
                }
            }
        }
    },

    query:{
        byId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"_id",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        mapId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"mapId",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        mapIdAndType:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"mapId",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        },
                        1:{
                            cloumn:"type",
                            value:{
                                map:"subId",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    validation:{
        errors:{
            nameHash:{
                mapTo:'name',
                messages:{
                    11000:'Duplicate name is not allowed'
                }
            },
            roleMappingHash:{
                mapTo:'roleMapping',
                messages:{
                    11000:'Duplicate role mapping is not allowed'
                }
            }
        }
    },

    values:{
        infoDetails:{
            default:{},
            exclude:{},
            hardcoded:{},
        }
    }
}