module.exports = {
    src:{
        dvalue:'',
        type:'string',
        description:"Specifies the source URL or path of the image to be displayed. The value can be a local asset path, a remote URL, or a dynamically generated image source."
    },
    wrap:{
        dvalue:false,
        type:"boolean",
        description:"Specifies a custom React element or component used to wrap the image. This allows customization of the image's surrounding structure, enabling additional styling, layout control, or interactive behavior."
    },
    dsTheme:{
        description:"A predefined collection of styles, design tokens, and component configurations that apply a consistent visual appearance and behavior across an application. Presets help teams quickly adopt established design standards by bundling typography, colors, spacing, themes, and component variations into reusable configurations.",
        type:"predefined",
        ___:{
            predefined:{
                from:'statics',
                mapping:'ds.preset',
                overwirte:{
                    radius:{
                        dvalue:"4"
                    },
                    image__d__thumbnail:{
                        dvalue:28
                    }
                }
            }
        },
    },
    config:{
        type:'nested',
        description:"",
        ___:{
            nested:{
                image:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:null,
                                ds:{
                                    ___:{
                                        nested:{
                                            predefined:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            background:{}
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                wrapper:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                },
                                ds:{
                                    ___:{
                                        nested:{
                                            predefined:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            radius:{}
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}