const required = (type, createReq) => {
    let req = createReq?'required':'optional';

    if(type === 'update' && !createReq){
        req = 'optional';
    }

    return {
        "value":req,
        "uivalue":req,
        "bothAreSame":true
    }
}

const hexcode = (type, createReq) => {
    return {
        "message":{
            "error":{
                "checks":{
                    "required":"Color hex code is required",
                    "regex":"Please provide vaild color hex code"
                }
            }
        },
        "checks":{
            "regex":{
                "bothAreSame":true,
                "value":'^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$',
                "uivalue":'^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$'
            },
            "required":required(type, createReq)
        }
    }
}

const body = (type) => {
    return {
        "name":{
            "message":{
                "error":{
                    "checks":{
                        "required":"TTheme name is required field."
                    }
                }, 
                "success":{
                    "default":"IN",
                    "checks":{
                        "required":"Theme name is required field."
                    }
                }
            },
            "checks":{
                "required":required(type)
            }
        },
        "code":{
            "message":{
                "error":{
                    "checks":{
                        "required":"Theme code is required field."
                    }
                }, 
                "success":{
                    "default":"IN",
                    "checks":{
                        "required":"Theme code is required field."
                    }
                }
            },
            "checks":{
                "required":required(type)
            }
        },
        "parentId":{
            "message":{
                "error":{
                    "checks":{
                        "regex":"Please provide vaild id",
                        "minlength":"Please provide vaild id",
                        "maxlength":"Please provide vaild id",
                        "required":"Please provide vaild id"
                    }
                }
            },
            "checks":{
                "regex":{
                    "bothAreSame":true,
                    "value":'^[a-zA-Z0-9]+$',
                    "uivalue":'^[a-zA-Z0-9]+$',
                },
                "minlength":{
                    "value":32
                },
                "maxlength":{
                    "value":32
                },
                "required":required(type)
            }
        },
        "details.colors.0.types.0.shades.0.hex":hexcode(type, true),
        "details.colors.0.types.0.shades.1.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.0.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.1.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.2.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.3.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.4.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.5.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.6.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.7.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.8.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.9.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.10.hex":hexcode(type, true),
        "details.colors.0.types.1.shades.11.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.0.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.1.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.2.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.3.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.4.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.5.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.6.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.7.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.8.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.9.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.10.hex":hexcode(type, true),
        "details.colors.0.types.2.shades.11.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.0.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.1.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.2.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.3.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.4.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.5.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.6.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.7.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.8.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.9.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.10.hex":hexcode(type, true),
        "details.colors.0.types.3.shades.11.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.0.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.1.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.2.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.3.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.4.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.5.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.6.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.7.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.8.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.9.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.10.hex":hexcode(type, true),
        "details.colors.0.types.4.shades.11.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.0.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.1.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.2.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.3.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.4.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.5.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.6.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.7.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.8.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.9.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.10.hex":hexcode(type, true),
        "details.colors.0.types.5.shades.11.hex":hexcode(type, true),
        "details.colors.1.types.0.shades.0.hex":hexcode(type),
        "details.colors.1.types.0.shades.1.hex":hexcode(type),
        "details.colors.1.types.0.shades.2.hex":hexcode(type),
        "details.colors.1.types.0.shades.3.hex":hexcode(type),
        "details.colors.1.types.0.shades.4.hex":hexcode(type),
        "details.colors.1.types.0.shades.5.hex":hexcode(type),
        "details.colors.1.types.0.shades.6.hex":hexcode(type),
        "details.colors.1.types.0.shades.7.hex":hexcode(type),
        "details.colors.1.types.0.shades.8.hex":hexcode(type),
        "details.colors.1.types.0.shades.9.hex":hexcode(type),
        "details.colors.1.types.0.shades.10.hex":hexcode(type),
        "details.colors.1.types.0.shades.11.hex":hexcode(type),
        "details.colors.1.types.1.shades.0.hex":hexcode(type),
        "details.colors.1.types.1.shades.1.hex":hexcode(type),
        "details.colors.1.types.1.shades.2.hex":hexcode(type),
        "details.colors.1.types.1.shades.3.hex":hexcode(type),
        "details.colors.1.types.1.shades.4.hex":hexcode(type),
        "details.colors.1.types.1.shades.5.hex":hexcode(type),
        "details.colors.1.types.1.shades.6.hex":hexcode(type),
        "details.colors.1.types.1.shades.7.hex":hexcode(type),
        "details.colors.1.types.1.shades.8.hex":hexcode(type),
        "details.colors.1.types.1.shades.9.hex":hexcode(type),
        "details.colors.1.types.1.shades.10.hex":hexcode(type),
        "details.colors.1.types.1.shades.11.hex":hexcode(type),
        "details.colors.1.types.2.shades.0.hex":hexcode(type),
        "details.colors.1.types.2.shades.1.hex":hexcode(type),
        "details.colors.1.types.2.shades.2.hex":hexcode(type),
        "details.colors.1.types.2.shades.3.hex":hexcode(type),
        "details.colors.1.types.2.shades.4.hex":hexcode(type),
        "details.colors.1.types.2.shades.5.hex":hexcode(type),
        "details.colors.1.types.2.shades.6.hex":hexcode(type),
        "details.colors.1.types.2.shades.7.hex":hexcode(type),
        "details.colors.1.types.2.shades.8.hex":hexcode(type),
        "details.colors.1.types.2.shades.9.hex":hexcode(type),
        "details.colors.1.types.2.shades.10.hex":hexcode(type),
        "details.colors.1.types.2.shades.11.hex":hexcode(type),
        "details.colors.1.types.3.shades.0.hex":hexcode(type),
        "details.colors.1.types.3.shades.1.hex":hexcode(type),
        "details.colors.1.types.3.shades.2.hex":hexcode(type),
        "details.colors.1.types.3.shades.3.hex":hexcode(type),
        "details.colors.1.types.3.shades.4.hex":hexcode(type),
        "details.colors.1.types.3.shades.5.hex":hexcode(type),
        "details.colors.1.types.3.shades.6.hex":hexcode(type),
        "details.colors.1.types.3.shades.7.hex":hexcode(type),
        "details.colors.1.types.3.shades.8.hex":hexcode(type),
        "details.colors.1.types.3.shades.9.hex":hexcode(type),
        "details.colors.1.types.3.shades.10.hex":hexcode(type),
        "details.colors.1.types.3.shades.11.hex":hexcode(type),
        "details.colors.1.types.4.shades.0.hex":hexcode(type),
        "details.colors.1.types.4.shades.1.hex":hexcode(type),
        "details.colors.1.types.4.shades.2.hex":hexcode(type),
        "details.colors.1.types.4.shades.3.hex":hexcode(type),
        "details.colors.1.types.4.shades.4.hex":hexcode(type),
        "details.colors.1.types.4.shades.5.hex":hexcode(type),
        "details.colors.1.types.4.shades.6.hex":hexcode(type),
        "details.colors.1.types.4.shades.7.hex":hexcode(type),
        "details.colors.1.types.4.shades.8.hex":hexcode(type),
        "details.colors.1.types.4.shades.9.hex":hexcode(type),
        "details.colors.1.types.4.shades.10.hex":hexcode(type),
        "details.colors.1.types.4.shades.11.hex":hexcode(type),
        "details.colors.1.types.5.shades.0.hex":hexcode(type),
        "details.colors.1.types.5.shades.1.hex":hexcode(type),
        "details.colors.1.types.5.shades.2.hex":hexcode(type),
        "details.colors.1.types.5.shades.3.hex":hexcode(type),
        "details.colors.1.types.5.shades.4.hex":hexcode(type),
        "details.colors.1.types.5.shades.5.hex":hexcode(type),
        "details.colors.1.types.5.shades.6.hex":hexcode(type),
        "details.colors.1.types.5.shades.7.hex":hexcode(type),
        "details.colors.1.types.5.shades.8.hex":hexcode(type),
        "details.colors.1.types.5.shades.9.hex":hexcode(type),
        "details.colors.1.types.5.shades.10.hex":hexcode(type),
        "details.colors.1.types.5.shades.11.hex":hexcode(type),
        "details.colors.1.types.6.shades.0.hex":hexcode(type),
        "details.colors.1.types.6.shades.1.hex":hexcode(type),
        "details.colors.1.types.6.shades.2.hex":hexcode(type),
        "details.colors.1.types.6.shades.3.hex":hexcode(type),
        "details.colors.1.types.6.shades.4.hex":hexcode(type),
        "details.colors.1.types.6.shades.5.hex":hexcode(type),
        "details.colors.1.types.6.shades.6.hex":hexcode(type),
        "details.colors.1.types.6.shades.7.hex":hexcode(type),
        "details.colors.1.types.6.shades.8.hex":hexcode(type),
        "details.colors.1.types.6.shades.9.hex":hexcode(type),
        "details.colors.1.types.6.shades.10.hex":hexcode(type),
        "details.colors.1.types.6.shades.11.hex":hexcode(type),
        "details.colors.1.types.7.shades.0.hex":hexcode(type),
        "details.colors.1.types.7.shades.1.hex":hexcode(type),
        "details.colors.1.types.7.shades.2.hex":hexcode(type),
        "details.colors.1.types.7.shades.3.hex":hexcode(type),
        "details.colors.1.types.7.shades.4.hex":hexcode(type),
        "details.colors.1.types.7.shades.5.hex":hexcode(type),
        "details.colors.1.types.7.shades.6.hex":hexcode(type),
        "details.colors.1.types.7.shades.7.hex":hexcode(type),
        "details.colors.1.types.7.shades.8.hex":hexcode(type),
        "details.colors.1.types.7.shades.9.hex":hexcode(type),
        "details.colors.1.types.7.shades.10.hex":hexcode(type),
        "details.colors.1.types.7.shades.11.hex":hexcode(type),
        "details.colors.1.types.8.shades.0.hex":hexcode(type),
        "details.colors.1.types.8.shades.1.hex":hexcode(type),
        "details.colors.1.types.8.shades.2.hex":hexcode(type),
        "details.colors.1.types.8.shades.3.hex":hexcode(type),
        "details.colors.1.types.8.shades.4.hex":hexcode(type),
        "details.colors.1.types.8.shades.5.hex":hexcode(type),
        "details.colors.1.types.8.shades.6.hex":hexcode(type),
        "details.colors.1.types.8.shades.7.hex":hexcode(type),
        "details.colors.1.types.8.shades.8.hex":hexcode(type),
        "details.colors.1.types.8.shades.9.hex":hexcode(type),
        "details.colors.1.types.8.shades.10.hex":hexcode(type),
        "details.colors.1.types.8.shades.11.hex":hexcode(type),
        "details.colors.1.types.9.shades.0.hex":hexcode(type),
        "details.colors.1.types.9.shades.1.hex":hexcode(type),
        "details.colors.1.types.9.shades.2.hex":hexcode(type),
        "details.colors.1.types.9.shades.3.hex":hexcode(type),
        "details.colors.1.types.9.shades.4.hex":hexcode(type),
        "details.colors.1.types.9.shades.5.hex":hexcode(type),
        "details.colors.1.types.9.shades.6.hex":hexcode(type),
        "details.colors.1.types.9.shades.7.hex":hexcode(type),
        "details.colors.1.types.9.shades.8.hex":hexcode(type),
        "details.colors.1.types.9.shades.9.hex":hexcode(type),
        "details.colors.1.types.9.shades.10.hex":hexcode(type),
        "details.colors.1.types.9.shades.11.hex":hexcode(type),
        "details.colors.1.types.10.shades.0.hex":hexcode(type),
        "details.colors.1.types.10.shades.1.hex":hexcode(type),
        "details.colors.1.types.10.shades.2.hex":hexcode(type),
        "details.colors.1.types.10.shades.3.hex":hexcode(type),
        "details.colors.1.types.10.shades.4.hex":hexcode(type),
        "details.colors.1.types.10.shades.5.hex":hexcode(type),
        "details.colors.1.types.10.shades.6.hex":hexcode(type),
        "details.colors.1.types.10.shades.7.hex":hexcode(type),
        "details.colors.1.types.10.shades.8.hex":hexcode(type),
        "details.colors.1.types.10.shades.9.hex":hexcode(type),
        "details.colors.1.types.10.shades.10.hex":hexcode(type),
        "details.colors.1.types.10.shades.11.hex":hexcode(type),
        "details.colors.1.types.11.shades.0.hex":hexcode(type),
        "details.colors.1.types.11.shades.1.hex":hexcode(type),
        "details.colors.1.types.11.shades.2.hex":hexcode(type),
        "details.colors.1.types.11.shades.3.hex":hexcode(type),
        "details.colors.1.types.11.shades.4.hex":hexcode(type),
        "details.colors.1.types.11.shades.5.hex":hexcode(type),
        "details.colors.1.types.11.shades.6.hex":hexcode(type),
        "details.colors.1.types.11.shades.7.hex":hexcode(type),
        "details.colors.1.types.11.shades.8.hex":hexcode(type),
        "details.colors.1.types.11.shades.9.hex":hexcode(type),
        "details.colors.1.types.11.shades.10.hex":hexcode(type),
        "details.colors.1.types.11.shades.11.hex":hexcode(type),
        "details.colors.1.types.12.shades.0.hex":hexcode(type),
        "details.colors.1.types.12.shades.1.hex":hexcode(type),
        "details.colors.1.types.12.shades.2.hex":hexcode(type),
        "details.colors.1.types.12.shades.3.hex":hexcode(type),
        "details.colors.1.types.12.shades.4.hex":hexcode(type),
        "details.colors.1.types.12.shades.5.hex":hexcode(type),
        "details.colors.1.types.12.shades.6.hex":hexcode(type),
        "details.colors.1.types.12.shades.7.hex":hexcode(type),
        "details.colors.1.types.12.shades.8.hex":hexcode(type),
        "details.colors.1.types.12.shades.9.hex":hexcode(type),
        "details.colors.1.types.12.shades.10.hex":hexcode(type),
        "details.colors.1.types.12.shades.11.hex":hexcode(type),
        "details.colors.1.types.13.shades.0.hex":hexcode(type),
        "details.colors.1.types.13.shades.1.hex":hexcode(type),
        "details.colors.1.types.13.shades.2.hex":hexcode(type),
        "details.colors.1.types.13.shades.3.hex":hexcode(type),
        "details.colors.1.types.13.shades.4.hex":hexcode(type),
        "details.colors.1.types.13.shades.5.hex":hexcode(type),
        "details.colors.1.types.13.shades.6.hex":hexcode(type),
        "details.colors.1.types.13.shades.7.hex":hexcode(type),
        "details.colors.1.types.13.shades.8.hex":hexcode(type),
        "details.colors.1.types.13.shades.9.hex":hexcode(type),
        "details.colors.1.types.13.shades.10.hex":hexcode(type),
        "details.colors.1.types.13.shades.11.hex":hexcode(type),
        "details.colors.1.types.14.shades.0.hex":hexcode(type),
        "details.colors.1.types.14.shades.1.hex":hexcode(type),
        "details.colors.1.types.14.shades.2.hex":hexcode(type),
        "details.colors.1.types.14.shades.3.hex":hexcode(type),
        "details.colors.1.types.14.shades.4.hex":hexcode(type),
        "details.colors.1.types.14.shades.5.hex":hexcode(type),
        "details.colors.1.types.14.shades.6.hex":hexcode(type),
        "details.colors.1.types.14.shades.7.hex":hexcode(type),
        "details.colors.1.types.14.shades.8.hex":hexcode(type),
        "details.colors.1.types.14.shades.9.hex":hexcode(type),
        "details.colors.1.types.14.shades.10.hex":hexcode(type),
        "details.colors.1.types.14.shades.11.hex":hexcode(type),
        "details.colors.1.types.15.shades.0.hex":hexcode(type),
        "details.colors.1.types.15.shades.1.hex":hexcode(type),
        "details.colors.1.types.15.shades.2.hex":hexcode(type),
        "details.colors.1.types.15.shades.3.hex":hexcode(type),
        "details.colors.1.types.15.shades.4.hex":hexcode(type),
        "details.colors.1.types.15.shades.5.hex":hexcode(type),
        "details.colors.1.types.15.shades.6.hex":hexcode(type),
        "details.colors.1.types.15.shades.7.hex":hexcode(type),
        "details.colors.1.types.15.shades.8.hex":hexcode(type),
        "details.colors.1.types.15.shades.9.hex":hexcode(type),
        "details.colors.1.types.15.shades.10.hex":hexcode(type),
        "details.colors.1.types.15.shades.11.hex":hexcode(type),
        "details.colors.1.types.16.shades.0.hex":hexcode(type),
        "details.colors.1.types.16.shades.1.hex":hexcode(type),
        "details.colors.1.types.16.shades.2.hex":hexcode(type),
        "details.colors.1.types.16.shades.3.hex":hexcode(type),
        "details.colors.1.types.16.shades.4.hex":hexcode(type),
        "details.colors.1.types.16.shades.5.hex":hexcode(type),
        "details.colors.1.types.16.shades.6.hex":hexcode(type),
        "details.colors.1.types.16.shades.7.hex":hexcode(type),
        "details.colors.1.types.16.shades.8.hex":hexcode(type),
        "details.colors.1.types.16.shades.9.hex":hexcode(type),
        "details.colors.1.types.16.shades.10.hex":hexcode(type),
        "details.colors.1.types.16.shades.11.hex":hexcode(type),
        "details.colors.1.types.17.shades.0.hex":hexcode(type),
        "details.colors.1.types.17.shades.1.hex":hexcode(type),
        "details.colors.1.types.17.shades.2.hex":hexcode(type),
        "details.colors.1.types.17.shades.3.hex":hexcode(type),
        "details.colors.1.types.17.shades.4.hex":hexcode(type),
        "details.colors.1.types.17.shades.5.hex":hexcode(type),
        "details.colors.1.types.17.shades.6.hex":hexcode(type),
        "details.colors.1.types.17.shades.7.hex":hexcode(type),
        "details.colors.1.types.17.shades.8.hex":hexcode(type),
        "details.colors.1.types.17.shades.9.hex":hexcode(type),
        "details.colors.1.types.17.shades.10.hex":hexcode(type),
        "details.colors.1.types.17.shades.11.hex":hexcode(type),
        "details.colors.1.types.18.shades.0.hex":hexcode(type),
        "details.colors.1.types.18.shades.1.hex":hexcode(type),
        "details.colors.1.types.18.shades.2.hex":hexcode(type),
        "details.colors.1.types.18.shades.3.hex":hexcode(type),
        "details.colors.1.types.18.shades.4.hex":hexcode(type),
        "details.colors.1.types.18.shades.5.hex":hexcode(type),
        "details.colors.1.types.18.shades.6.hex":hexcode(type),
        "details.colors.1.types.18.shades.7.hex":hexcode(type),
        "details.colors.1.types.18.shades.8.hex":hexcode(type),
        "details.colors.1.types.18.shades.9.hex":hexcode(type),
        "details.colors.1.types.18.shades.10.hex":hexcode(type),
        "details.colors.1.types.18.shades.11.hex":hexcode(type),
        "details.colors.1.types.19.shades.0.hex":hexcode(type),
        "details.colors.1.types.19.shades.1.hex":hexcode(type),
        "details.colors.1.types.19.shades.2.hex":hexcode(type),
        "details.colors.1.types.19.shades.3.hex":hexcode(type),
        "details.colors.1.types.19.shades.4.hex":hexcode(type),
        "details.colors.1.types.19.shades.5.hex":hexcode(type),
        "details.colors.1.types.19.shades.6.hex":hexcode(type),
        "details.colors.1.types.19.shades.7.hex":hexcode(type),
        "details.colors.1.types.19.shades.8.hex":hexcode(type),
        "details.colors.1.types.19.shades.9.hex":hexcode(type),
        "details.colors.1.types.19.shades.10.hex":hexcode(type),
        "details.colors.1.types.19.shades.11.hex":hexcode(type),
        "details.colors.1.types.21.shades.0.hex":hexcode(type),
        "details.colors.1.types.21.shades.1.hex":hexcode(type),
        "details.colors.1.types.21.shades.2.hex":hexcode(type),
        "details.colors.1.types.21.shades.3.hex":hexcode(type),
        "details.colors.1.types.21.shades.4.hex":hexcode(type),
        "details.colors.1.types.21.shades.5.hex":hexcode(type),
        "details.colors.1.types.21.shades.6.hex":hexcode(type),
        "details.colors.1.types.21.shades.7.hex":hexcode(type),
        "details.colors.1.types.21.shades.8.hex":hexcode(type),
        "details.colors.1.types.21.shades.9.hex":hexcode(type),
        "details.colors.1.types.21.shades.10.hex":hexcode(type),
        "details.colors.1.types.21.shades.11.hex":hexcode(type),
        "details.colors.1.types.22.shades.0.hex":hexcode(type),
        "details.colors.1.types.22.shades.1.hex":hexcode(type),
        "details.colors.1.types.22.shades.2.hex":hexcode(type),
        "details.colors.1.types.22.shades.3.hex":hexcode(type),
        "details.colors.1.types.22.shades.4.hex":hexcode(type),
        "details.colors.1.types.22.shades.5.hex":hexcode(type),
        "details.colors.1.types.22.shades.6.hex":hexcode(type),
        "details.colors.1.types.22.shades.7.hex":hexcode(type),
        "details.colors.1.types.22.shades.8.hex":hexcode(type),
        "details.colors.1.types.22.shades.9.hex":hexcode(type),
        "details.colors.1.types.22.shades.10.hex":hexcode(type),
        "details.colors.1.types.22.shades.11.hex":hexcode(type),
        "details.colors.1.types.23.shades.0.hex":hexcode(type),
        "details.colors.1.types.23.shades.1.hex":hexcode(type),
        "details.colors.1.types.23.shades.2.hex":hexcode(type),
        "details.colors.1.types.23.shades.3.hex":hexcode(type),
        "details.colors.1.types.23.shades.4.hex":hexcode(type),
        "details.colors.1.types.23.shades.5.hex":hexcode(type),
        "details.colors.1.types.23.shades.6.hex":hexcode(type),
        "details.colors.1.types.23.shades.7.hex":hexcode(type),
        "details.colors.1.types.23.shades.8.hex":hexcode(type),
        "details.colors.1.types.23.shades.9.hex":hexcode(type),
        "details.colors.1.types.23.shades.10.hex":hexcode(type),
        "details.colors.1.types.23.shades.11.hex":hexcode(type)
    }
}

const rval = {
    create:body('create'),
    update:body('update'),
}

module.exports = rval;