const messages = process.aioBeLibs('helpers/_private/utils/messages');
// 'fb72d5e5b3d14ac9e454ffe3fe6a879b' <==== helpers.crpt.md5('aio_aiodeals.com_aio') === DON'T REMOVE THIS AS THIS IS IMPORTANT

module.exports = {
    date:{
        format:{
            YYYY_MM_DD:{
                message:messages.regex.date.format.YYYY_MM_DD,
                value:'^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])(T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z)?$'
            }
        }
    },
    mobile:{
        dom:{
            value:'^[6-9]\\d{9}$',
            message:messages.regex.mobile.dom
        },
        int:{
            value:'^[1-9]\\d{7,14}$',
            message:messages.regex.mobile.int
        }
    },
    otp:{
        value:'^\\d{6}$',
        message:messages.regex.otp
    },
    empId:{
        value:'^[1-9]\\d{0,5}$',
        message:messages.regex.empId
    },
    email:{
        value:'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$',
        message:messages.regex.email
    },
    username:{
        value:'^(?![_.])(?!.*[_.]{2})[a-zA-Z][a-zA-Z0-9._]{2,19}(?<![_.])$',
        message:messages.regex.username
    },
    password:{
        value:'^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()])[A-Za-z\\d!@#$%^&*()]{8,16}$',
        message:messages.regex.password
    },
    numberOnly:{
        value:'^\\d+$',
        message:messages.regex.numberOnly
    },
    string:{
        encoded:{
            value:'^(?=.{10,}$)(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$',
            message:messages.regex.string.encoded
        }
    },
    token:{
        value:'^(?=.{10,}$)(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$',
        message:messages.regex.token
    },
    md5Hash:{
        value:'^(?:[a-zA-Z0-9]{32})?$',
        message:messages.regex.md5Hash
    },
    mongoId:{
        value:'^(?:[a-zA-Z0-9]{24})?$',
        message:messages.regex.mongoId
    },
    alphabets:{
        key:{
            value:'^[A-Za-z]+$',
            message:messages.regex.alphabets
        }
    },
    name:{
        fn:{
            value:"^[A-Za-z'-]{2,30}$",
            message:messages.regex.name.fn
        },
        mn:{
            value:"^[A-Za-z'-]{2,30}$",
            message:messages.regex.name.mn
        },
        ln:{
            value:"^[A-Za-z'-]{2,30}$",
            message:messages.regex.name.ln
        },
        fmn:{
            value:"^([A-Za-z'-]{2,})(\\s[A-Za-z'-]{2,})*$",
            message:messages.regex.name.fmn
        }
    },
    address:{
        line1:{
            value:"^[a-zA-Z0-9\\s,'\\-/#.]{5,100}$",
            message:messages.regex.address.line1
        },
        line2:{
            value:"^[a-zA-Z0-9\\s,'\\-/#.()]{0,100}$",
            message:messages.regex.address.line2
        },
        landmark:{
            value:"^[a-zA-Z0-9\\s,'\\-/#().]{3,100}$",
            message:messages.regex.address.landmark
        },
        pincode:{
            value:"^[1-9][0-9]{5}$",
            message:messages.regex.address.pincode
        },
        city:{
            value:"^([A-Za-z'-]{2,})(\\s[A-Za-z'-]{2,})*$",
            message:messages.regex.address.city
        }
    },
    country:{
        name:{
            value:"^[A-Za-z]+(?:\s[A-Za-z]+)*$",
            message:messages.regex.country.name
        }
    },
    text:{
        key:{
            value:"^[A-Za-z]+(-[A-Za-z]+)*$",
            message:messages.regex.text.code,
        },
        code:{
            value:"^[A-Z]+(-[A-Z]+)*$",
            message:messages.regex.text.code,
        },
        lowerCode:{
            value:"^[a-z]+(-[a-z]+)*$",
            message:messages.regex.text.lowerCode,
        },
        richtext:{
            message:messages.regex.text.richtext,
            value:"^(?:[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=\\s]+(?:\\r?\\n(?!\\r?\\n)[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=\\s]+)*)(?:\\r?\\n\\r?\\n(?:[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=\\s]+(?:\\r?\\n(?!\\r?\\n)[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=\\s]+)*))*$"
        },
        paragraph:{
            message:messages.regex.text.paragraph,
            value:"^[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=]+$",
        },
        paragraphs:{
            message:messages.regex.text.paragraphs,
            value:"^(?:[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=\\s]+(?:\\r?\\n(?!\\r?\\n)[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=\\s]+)*)(?:\\r?\\n\\r?\\n(?:[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=\\s]+(?:\\r?\\n(?!\\r?\\n)[A-Za-z0-9_.,'\"\\-!?;:()<>\\/=\\s]+)*))*$",
        }
    },
    stringmap:{
        message:messages.regex.stringmap,
        value:'^(?:[A-Za-z0-9]{32})(?:\\\.[A-Za-z0-9]{32})*$'
    },
    hashmap:{
        optional:{
            message:messages.regex.hashmap.optional,
            value:'^(?:[A-Za-z0-9]{32})(?:\.[A-Za-z0-9]{32})*\.fb72d5e5b3d14ac9e454ffe3fe6a879b$'
        },
        required:{
            message:messages.regex.hashmap.required,
            value:"^[A-Za-z0-9]{32}(?:\.[A-Za-z0-9]{32})?$"
        }
    },
    idmap:{
        optional:{
            message:messages.regex.idmap.optional,
            value:'^(?:[A-Za-z0-9]{24})(?:\.[A-Za-z0-9]{24})*\.691e19219926d98951234abc'
        },
        required:{
            message:messages.regex.idmap.required,
            value:'^(?:[A-Za-z0-9]{24})(?:\\\.[A-Za-z0-9]{24})*$'
        }
    },
    number:{
        only:{
            value:'^\\d+$',
            message:messages.regex.number.only
        }
        
    },
}