module.exports = {
    content:{
        type:"any",
        dvalue:'',
        description:"A prop used to pass content into a component. It can contain renderable React content such as JSX elements, strings, numbers, booleans, fragments, arrays of elements, or null/undefined. In some cases, it may also accept a function (render prop) that returns React content, allowing dynamic rendering based on component state or props.",
    },

    avatars:{
        type:'nested',
        description:"",
        ___:{
            nested:{
                right:{
                    type:'compProps',
                    description:"",
                    ___:{
                        asroot:false,
                        compProps:{
                            from:'statics',
                            mapping:'raw/atoms/avatar',
                            overwirte:{
                                enable:{
                                    dvalue:false,
                                    type:'boolean'
                                }
                            }
                        }
                    }
                },
                left:{
                    type:'compProps',
                    description:"",
                    ___:{
                        asroot:false,
                        compProps:{
                            from:'statics',
                            mapping:'raw/atoms/avatar',
                            overwirte:{
                                enable:{
                                    dvalue:false,
                                    type:'boolean'
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    icons:{
        type:'nested',
        description:"",
        ___:{
            nested:{
                left:{
                    type:'compProps',
                    description:"",
                    ___:{
                        asroot:false,
                        compProps:{
                            from:'statics',
                            mapping:'raw/atoms/icons',
                            overwirte:{
                                config:{
                                    ___:{
                                        predefined:{
                                            overwirte:{
                                                icon:{
                                                    ___:{
                                                        nested:{
                                                            name:{
                                                                dvalue:'home'
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                right:{
                    type:'compProps',
                    description:"",
                    ___:{
                        asroot:false,
                        compProps:{
                            from:'statics',
                            mapping:'raw/atoms/icons',
                            overwirte:{
                                config:{
                                    ___:{
                                        predefined:{
                                            overwirte:{
                                                icon:{
                                                    ___:{
                                                        nested:{
                                                            name:{
                                                                dvalue:'bell'
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    config:{
        type:'nested',
        description:"",
        ___:{
            nested:{
                content:{
                    type:'predefined',
                    description:'',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'p'
                                            }
                                        }
                                    }
                                },
                                ds:{
                                    ___:{
                                        nested:{
                                            predefined:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            color:{},
                                                            background:{}
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                wrapper:{
                    type:'predefined',
                    description:'',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                },
                                ds:{
                                    ___:{
                                        nested:{
                                            predefined:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            radius:{
                                                                dvalue:'round'
                                                            },
                                                            color:{
                                                                dvalue:'c00108'
                                                            },
                                                            border:{
                                                                dvalue:'c00103'
                                                            },
                                                            background:{
                                                                dvalue:'c00101'
                                                            }
                                                        }
                                                    }
                                                }
                                            },
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    fontsize:{
                                                                        dvalue:'sm'
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }   
        }
    }
}