module.exports = {
    "schema":{
        "type":true
    },
    "values":{
        "hardcoded":{
            "type":"ds-theme"
        }
    },
    "response":{
        "exclude":{
            "enable":true,
            "kies":{
                "ts":true
            }
        },
        "transform":{
            "enable":true,
            "kies":{
                "_id":"id",
                "hashId":"hId",
            }
        }
    },

    "query":{
        "runtime":{
            "enable":true,
            "configs":{
                "query":{
                    "0":{
                        "cloumn":"hashId",
                        "value":{
                            "map":"id",
                            "from":"params"
                        },
                        "operation":{
                            "eq":{
                                "enable":true,
                                "opType":"eq"
                            }
                        }
                    },
                    "1":{
                        "cloumn":"type",
                        "value":{
                            "map":"type",
                            "from":"body-item"
                        },
                        "operation":{
                            "eq":{
                                "enable":true,
                                "opType":"eq"
                            }
                        }
                    }
                }
            }
        }
    },

    "signature":{
        "merge":{
            "enable":true
        },
        "creation":{
            "enable":true,
            "nodes":{
                "_id":{
                    "enable":true,
                    "valueType":"objectId"
                },
                "_merchantId":{
                    "enable":true,
                    "valueType":"objectId"
                }
            }
        }
    }
}