module.exports = {
    "hashId":{
        "nodes":{
            "0":{
                "map":"runtimeUtils.merchantRootHash",
                "from":"appConfig"
            },
            "1":{
                "map":"appConfig.applicationType",
                "from":"body-item"
            },
            "2":{
                "map":"appName",
                "from":"body-item"
            },
        }
    },
    "portHashId":{
        "nodes":{
            "0":{
                "map":"runtimeUtils.merchantRootHash",
                "from":"appConfig"
            },
            "1":{
                "map":"appConfig.ports.public",
                "from":"body-item"
            }
        }
    },
    "internalPortHashId":{
        "nodes":{
            "0":{
                "map":"runtimeUtils.merchantRootHash",
                "from":"appConfig"
            },
            "1":{
                "map":"appConfig.ports.internal",
                "from":"body-item"
            }
        }
    },
    "partnerPortHashId":{
        "nodes":{
            "0":{
                "map":"runtimeUtils.merchantRootHash",
                "from":"appConfig"
            },
            "1":{
                "map":"appConfig.ports.partner",
                "from":"body-item"
            }
        }
    },
    "schedulerPortHashId":{
        "nodes":{
            "0":{
                "map":"runtimeUtils.merchantRootHash",
                "from":"appConfig"
            },
            "1":{
                "map":"appConfig.ports.scheduler",
                "from":"body-item"
            }
        }
    }
}