module.exports = {
    "codeId":{
        "nodes":{
            "0":{
                "from":"appConfig",
                "map":"runtimeUtils.merchantRootHash"
            },
            "1":{
                "map":"parentId",
                "from":"body-item"
            },
            "2":{
                "map":"code",
                "from":"body-item"
            },
        }
    },
    "hashId":{
        "nodes":{
            "0":{
                "from":"appConfig",
                "map":"runtimeUtils.merchantRootHash"
            },
            "1":{
                "map":"parentId",
                "from":"body-item"
            },
            "2":{
                "map":"name",
                "from":"body-item"
            },
        }
    },
}