const helpers = process.uiHelpers();
const storybook = {
    predefined:process.aioAppConfigs('storybook/predefined')
}
const row = process.aioAppConfigs('storybook/raw/atoms/content-row');

const predefined = (arg) => {
    return helpers.json.merge({
        ___:{
            predefined:{
                overwirte:{
                    ds:{
                        ___:{
                            nested:{
                                theme:null,
                                predefined:null,
                                css:{
                                    ___:{
                                        nested:{
                                            class:{
                                                ___:{
                                                    nested:{
                                                        margin:{
                                                            ___:{
                                                                nested:{
                                                                    1:{
                                                                        dvalue:0
                                                                    },
                                                                    2:{
                                                                        dvalue:12
                                                                    },
                                                                    3:{
                                                                        dvalue:0
                                                                    },
                                                                    4:{
                                                                        dvalue:0
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }, arg || {});
}

const theme = (arg) => {
    return helpers.json.merge({
        type:'nested',
        ___:{
            nested:{
                theme:storybook.predefined.ds.theme,
                predefined:{
                    type:'nested',
                    description:"",
                    ___:{
                        nested:storybook.predefined.ds.preset
                    }
                }
            }
        }
    }, arg || {});
}

module.exports = helpers.json.merge(helpers.json.get(row, 'props', {}), {
    kies:{
        type:'nested',
        ___:{
            nested:{
                label:{
                    type:'string',
                    dvalue:'label',
                    description:'',
                }
            }
        }
    },
    data:{
        dvalue:{},
        type:'object',
        description:''
    },
    disabled:{
        dvalue:false,
        type:'boolean',
        description:"This flag sets that item is in disabled mode if the value of this prop set as true."
    },
    state:{
        type:"enum",
        dvalue:'default',
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"list.item.states"
            }
        }
    },
    theme:{
        type:'nested',
        ___:{
            nested:{
                default:{
                    type:'nested',
                    ___:{
                        nested:{
                            end:theme(),
                            after:theme(),
                            start:theme(),
                            before:theme(),
                            center:theme(),
                            wrapper:theme({
                                ___:{
                                    nested:{
                                        predefined:{
                                            ___:{
                                                nested:{
                                                    color:{
                                                        dvalue:'c00110'
                                                    },
                                                    background:{
                                                        dvalue:'c00000'
                                                    },
                                                    hbackground:{
                                                        dvalue:'c00101'
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            })
                        }
                    }
                },
                selected:{
                    type:'nested',
                    ___:{
                        nested:{
                            end:theme(),
                            after:theme(),
                            start:theme(),
                            before:theme(),
                            center:theme(),
                            wrapper:theme({
                                ___:{
                                    nested:{
                                        predefined:{
                                            ___:{
                                                nested:{
                                                    background:{
                                                        dvalue:'c00101'
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            })
                        }
                    }
                },
                disabled:{
                    type:'nested',
                    ___:{
                        nested:{
                            end:theme(),
                            after:theme(),
                            start:theme(),
                            before:theme(),
                            center:theme(),
                            wrapper:theme({
                                ___:{
                                    nested:{
                                        predefined:{
                                            ___:{
                                                nested:{
                                                    color:{
                                                        dvalue:'c00105'
                                                    },
                                                    background:{
                                                        dvalue:'c00101'
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            })
                        }
                    }
                }
            }
        }
    },
    config:{
        ___:{
            nested:{
                start:predefined(),
                before:predefined(),
                center:predefined({
                    ___:{
                        predefined:{
                            overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            theme:null,
                                            predefined:null,
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    margin:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:0
                                                                                },
                                                                                2:{
                                                                                    dvalue:0
                                                                                },
                                                                                3:{
                                                                                    dvalue:0
                                                                                },
                                                                                4:{
                                                                                    dvalue:0
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }),
                end:predefined({
                    ___:{
                        predefined:{
                            overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    margin:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:0
                                                                                },
                                                                                2:{
                                                                                    dvalue:0
                                                                                },
                                                                                3:{
                                                                                    dvalue:0
                                                                                },
                                                                                4:{
                                                                                    dvalue:12
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }),
                after:predefined({
                    ___:{
                        predefined:{
                            overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    margin:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:0
                                                                                },
                                                                                2:{
                                                                                    dvalue:0
                                                                                },
                                                                                3:{
                                                                                    dvalue:0
                                                                                },
                                                                                4:{
                                                                                    dvalue:12
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }),
                wrapper:{
                    ___:{
                        predefined:{
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'li'
                                            }
                                        }
                                    }
                                },
                                ds:{
                                    ___:{
                                        nested:{
                                            theme:null,
                                            predefined:null,
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    cursor:{
                                                                        dvalue:'cp'
                                                                    },
                                                                    family:{
                                                                        dvalue:'sm'   
                                                                    },
                                                                    fontsize:{
                                                                        dvalue:'sm'   
                                                                    },
                                                                    padding:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:10
                                                                                },
                                                                                2:{
                                                                                    dvalue:14
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
})