module.exports = {
    config:{
         type:'predefined',
        ___:{
            predefined:{
                from:'statics',
                mapping:'ds.configs',
                overwirte:{
                    markup:{
                        type:'nested',
                        ___:{
                            nested:{
                                element:{
                                    dvalue:'h1'
                                }
                            }
                        }
                    },
                    ds:{
                        type:'nested',
                        ___:{
                            nested:{
                                css:{
                                    type:'nested',
                                    ___:{
                                        nested:{
                                            class:{
                                                type:'nested',
                                                ___:{
                                                    nested:{
                                                        family:{
                                                            dvalue:'md',
                                                        },
                                                        fontsize:{
                                                            dvalue:'xxl',
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    } 
                                },
                                flags:{
                                    type:'nested',
                                    ___:{
                                        nested:{
                                            isDisplay:{
                                                dvalue:true
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}