module.exports = {
    callback: {
        description:"Callback functions",
        type:"nested",
        ___:{
            nested:{
                onClick:{
                    type:'function'
                }
            }
        }
    },
    config:{
       type:'predefined',
        description:"Default button",
        ___:{
            predefined:{
                from:'statics',
                mapping:'ds.configs',
                overwirte:{
                    svg:null,
                    type:null,
                    markup:{
                        ___:{
                            nested:{
                                element:{
                                    dvalue:'span'
                                }
                            }
                        }
                    },
                    icon:{
                        type:'nested',
                        ___:{
                            nested:{
                                name:{
                                    type:'string'
                                },
                                size:{
                                    type:'enum',
                                    dvalue:'24',
                                    ___:{
                                        enum:{
                                            from:'statics',
                                            mapping:'icons.sizes'
                                        }
                                    }
                                },
                                family:{
                                    type:'enum',
                                    dvalue:'g',
                                    ___:{
                                        enum:{
                                            from:'statics',
                                            mapping:'icons.family'
                                        }
                                    }
                                }
                            }
                        }
                    },
                    dataAttrIconConfig:{
                        dvalue:false,
                        type:'boolean'
                    }
                }
            }
        }
    }
}