module.exports = {
    wrap:{
        dvalue:false,
        type:"boolean",
        description:"Specifies a custom React element or component used to wrap the layer element. This allows customization of the image's surrounding structure, enabling additional styling, layout control, or interactive behavior."
    },

    templates:{
        description:"Layer releated configuration like as size of layer, alignment and dimensions",
        type:"nested",
        ___:{
            nested:{
                layer:{
                    type:'any',
                    dvalue:''
                },
                content:{
                    type:'any',
                    dvalue:''
                }
            }
        }
    },

    layer:{
        description:"Layer releated configuration like as size of layer, alignment and dimensions",
        type:"nested",
        ___:{
            nested:{
                align:{
                    dvalue:'c',
                    type:"enum",
                    description:"Specifies the font family used by the component. Use this property to select the appropriate typeface according to the design system's typography guidelines.",
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:"layer.align"
                        }
                    }
                },
                size:{
                    dvalue:24,
                    type:"enum",
                    description:"Specifies the font family used by the component. Use this property to select the appropriate typeface according to the design system's typography guidelines.",
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:"global.spaces"
                        }
                    }
                },
                dimensions:{
                    type:"nested",
                    description:"Specifies the font family used by the component. Use this property to select the appropriate typeface according to the design system's typography guidelines.",
                    ___:{
                        nested:{
                            width:{
                                dvalue:'',
                                type:"enum",
                                description:"Specifies the font family used by the component. Use this property to select the appropriate typeface according to the design system's typography guidelines.",
                                ___:{
                                    enum:{
                                        from:'statics',
                                        mapping:"global.spaces"
                                    }
                                }
                            },
                            height:{
                                dvalue:'',
                                type:"enum",
                                description:"Specifies the font family used by the component. Use this property to select the appropriate typeface according to the design system's typography guidelines.",
                                ___:{
                                    enum:{
                                        from:'statics',
                                        mapping:"global.spaces"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    content:{
        type:'compProps',
        description:"Contains the configuration-to-props mapping for the component. Values defined here are transformed into component props and applied when the component is rendered.",
        ___:{
            asroot:false,
            compProps:{
                from:'statics',
                mapping:'raw/atoms/typography/text/description'
            }
        }
    },

    config:{
        type:'nested',
        description:"",
        ___:{
            nested:{
                wrapper:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                container:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                content:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                },
                                spaceFromLayer:{
                                    type:"enum",
                                    description:"Defines the external spacing applied to the top of the component.",
                                    ___:{
                                        enum:{
                                            from:'statics',
                                            mapping:"global.spaces"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                layer:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}