module.exports = {
    callback: {
        description:"Callback functions",
        type:"nested",
        ___:{
            nested:{
                onClick:{
                    type:'function'
                }
            }
        }
    },
    config:{
        type:'predefined',
        description:"Default button",
        ___:{
            predefined:{
                from:'statics',
                mapping:'ds.configs',
                overwirte:{
                    content:null,
                    markup:{
                        ___:{
                            nested:{
                                element:{
                                    dvalue:'span'
                                }
                            }
                        }
                    },
                    type:{
                        type:'enum',
                        dvalue:'font',
                        ___:{
                            enum:{
                                options:'font|svg'
                            }
                        }
                    },
                    svg:{
                        type:'nested',
                        ___:{
                            nested:{
                                src:{
                                    type:'string'
                                },
                                style:{
                                    dvalue:{},
                                    type:'object'
                                },
                                size:{
                                    type:'string',
                                    dvalue:'24px'
                                }
                            }
                        }
                    },
                    icon:{
                        type:'nested',
                        ___:{
                            nested:{
                                name:{
                                    dvalue:'home',
                                    type:'string'
                                },
                                size:{
                                    type:'enum',
                                    dvalue:'24',
                                    ___:{
                                        enum:{
                                            from:'statics',
                                            mapping:'icons.sizes'
                                        }
                                    }
                                },
                                family:{
                                    type:'enum',
                                    dvalue:'g',
                                    ___:{
                                        enum:{
                                            from:'statics',
                                            mapping:'icons.family'
                                        }
                                    }
                                }
                            }
                        }
                    },
                    dataAttrIconConfig:{
                        dvalue:false,
                        type:'boolean',
                        description:"Sets an HTML data-* attribute containing the icon configuration as a JSON string. The configuration captures icon details such as family, size, name, and type (e.g., font or svg).",
                    }
                }
            }
        }
    }
}