const schema = {
    name:true,
    hashId:true,
    exposed:true,
    code:true,
    codeHash:true,
    parentId: true,
    hasChilds: true,
    nameHashId: true,
    description: true,
    "details.value":true,
    "details.label":true,
    isAccessControlled:true
}

module.exports = {
    response:{
        exclude:{
            enable:true,
            kies:{
                ts:true,
                exposed:true,
                nameHashId:true
            }
        },
        transform:{
            enable:true,
            kies:{
                _id:"id"
            }
        }
    },
    valuemap: {
        name:{
            valuemap: {
                "map":"name",
                "from":"body-item"
            }
        },
        code:{
            valuemap: {
                "map":"code",
                "from":"body-item"
            }
        },
        hasChilds:{
            valuemap: {
                map:"hasChilds",
                from:"body-item"
            }
        },
        parentId:{
            valuemap: {
                map:"parentId",
                from:"body-item"
            }
        },
        rootParentId:{
            valuemap: {
                map:"runtimeUtils.merchantRootHash",
                from:"appConfig"
            }
        },
        isAccessControlled:{
            valuemap: {
                map:"isAccessControlled",
                from:"body-item"
            }
        }
    },

    md5Hash:{
        nameHashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"parentId",
                    from:"body-item"
                },
                2:{
                    map:"name",
                    from:"body-item"
                }
            }
        },
        rootNameHashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"name",
                    from:"body-item"
                }
            }
        },
        itemHashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"parentId",
                    from:"body-item"
                },
                2:{
                    map:"number",
                    from:"random"
                }
            }
        },
        rootHashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"number",
                    from:"random"
                }
            }
        },
        childCodeHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"parentId",
                    from:"body-item"
                },
                2:{
                    map:"code",
                    from:"body-item"
                }
            }
        },
        rootCodeHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"code",
                    from:"body-item"
                }
            }
        }
    },

    schema:schema,
    schemaByType:{
        details:{...schema, ...{}},
        update:{...schema, ...{hashId:false, parentId:false, code:false, codeHash:false}},
        updateDetails:{...schema, ...{hashId:false, parentId:false, code:false, codeHash:false}}
    },

    signature:{
        merge:{
            enable:true
        },
        creation:{
            enable:true,
            nodes:{
                _id:{
                    enable:true,
                    valueType:"objectId"
                },
                _merchantId:{
                    enable:true,
                    valueType:"objectId"
                }
            }
        }
    },

    query:{
        byId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"_id",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        hashId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"hashId",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        parentId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"parentId",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        merchantRootHash:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"parentId",
                            value:{
                                from:"appConfig",
                                map:"runtimeUtils.merchantRootHash"
                            },
                            operation:{
                                eq:{
                                    "enable":true,
                                    "opType":"eq"
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    validation:{
        errors:{
            nameHashId:{
                mapTo:'name',
                messages:{
                    11000:'Duplicate'
                }
            }
        }
    },

    values:{
        infoDetails:{
            default:{},
            exclude:{},
            hardcoded:{
                hasChilds:false
            },
        },
        parentDetail:{
            default:{},
            exclude:{},
            hardcoded:{
                hasChilds:true
            },
        }
    }
}