const helpers = process.uiHelpers();
const storybook = {
    predefined:process.aioAppConfigs('storybook/predefined')
}

const func = () => {
    return {
        dvalue:null,
        type:'function'
    }
}

const bool = (dval) => {
    return {
        type:'boolean',
        dvalue:dval || false
    }
}

const excludeTheme = (arg) => {
    return helpers.json.merge({
        ___:{
            predefined:{
                overwirte:{
                    ds:{
                        ___:{
                            nested:{
                                theme:null,
                                predefined:null
                            }
                        }
                    }
                }
            }
        }
    }, arg || {});
}

const theme = (arg) => {
    return {
        type:'nested',
        ___:{
            nested:{
                theme:helpers.json.merge(storybook.predefined.ds.theme, helpers.json.get(arg || {}, 'theme', {})),
                predefined:helpers.json.merge({
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.preset'
                        }
                    }
                }, {
                    ___:{
                        predefined:{
                            overwirte:helpers.json.get(arg || {}, 'predefined', {})
                        }
                    }
                }),
                
            }
        }
    }
}

const holderTheme = (arg) => {
    arg = arg || {};

    return {
        type:'nested',
        ___:{
            nested:{
                layer:theme(arg?.layer || {}),
                content:theme(arg?.content || {}),
                wrapper:theme(arg?.wrapper || {}),
                container:theme(arg?.container || {})
            }
        }
    }
}

module.exports = {
    mode:{
        type:"enum",
        dvalue:'checkbox',
        ___:{
            enum:{
                options:"checkbox|toggle|radio"
            }
        }
    },
    label:{
        type:"nested",
        ___:{
            nested:{
                text:{
                    dvalue:"",
                    type:"any",
                    description:"Accepts any valid value type, including <code>strings</code>, <code>numbers</code>, <code>booleans</code>, <code>functions</code>, <code>JSX elements</code>. The expected value depends on the component's implementation and the context in which the property is used."
                },
                config:{
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                             overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            theme:null,
                                            predefined:null,

                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    family:{
                                                                        dvalue:'md' 
                                                                    },
                                                                    fontsize:{
                                                                        dvalue:'sm'
                                                                    },
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'p'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    error:{
        type:"nested",
        ___:{
            nested:{
                text:{
                    dvalue:"",
                    type:"any",
                    description:"Accepts any valid value type, including <code>strings</code>, <code>numbers</code>, <code>booleans</code>, <code>functions</code>, <code>JSX elements</code>. The expected value depends on the component's implementation and the context in which the property is used."
                },
                config:{
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                             overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            theme:null,
                                            predefined:null,
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    fontsize:{
                                                                        dvalue:'xs'
                                                                    },
                                                                    margin:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:4
                                                                                },
                                                                                2:{
                                                                                    dvalue:0
                                                                                },
                                                                                3:{
                                                                                    dvalue:0
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'p'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    description:{
        type:"nested",
        ___:{
            nested:{
                text:{
                    dvalue:"",
                    type:"any",
                    description:"Accepts any valid value type, including <code>strings</code>, <code>numbers</code>, <code>booleans</code>, <code>functions</code>, <code>JSX elements</code>. The expected value depends on the component's implementation and the context in which the property is used."
                },
                config:{
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                             overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            theme:null,
                                            predefined:null,
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    fontsize:{
                                                                        dvalue:'xs'
                                                                    },
                                                                    margin:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:2
                                                                                },
                                                                                2:{
                                                                                    dvalue:0
                                                                                },
                                                                                3:{
                                                                                    dvalue:0
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'p'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    theme:{
        type:"nested", 
        ___:{
            nested:{
                default:{
                    type:"nested",
                    ___:{
                        nested:{
                            holder:holderTheme({
                                layer:{},
                                wrapper:{},
                                container:{},
                                content:{
                                    theme:{},
                                    predefined:{}
                                }
                            }),
                            error:theme({
                                theme:{},
                                predefined:{
                                    color:{
                                        dvalue:'c11008'
                                    },
                                    background:{}
                                }
                            }),
                            label:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{},
                                }
                            }),
                            description:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            checkbox:theme({
                                theme:{},
                                predefined:{
                                    background:{
                                        dvalue:'c00000'
                                    },
                                    border:{
                                        dvalue:'c10503'
                                    }
                                }
                            })
                        }
                    }
                },
                checked:{
                    type:"nested",
                    ___:{
                        nested:{
                            holder:holderTheme({
                                layer:{},
                                wrapper:{},
                                container:{},
                                content:{
                                    theme:{},
                                    predefined:{}
                                }
                            }),
                            error:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            label:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            description:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            checkbox:theme({
                                theme:{},
                                predefined:{
                                    bbackground:{
                                        dvalue:'c00000'
                                    },
                                    abackground:{
                                        dvalue:'c00000'
                                    },
                                    background:{
                                        dvalue:'c00207'
                                    },
                                    border:{
                                        dvalue:'c00207'
                                    }
                                }
                            })
                        }
                    }
                },
                disabled:{
                    type:"nested",
                    ___:{
                        nested:{
                            holder:holderTheme({
                                layer:{},
                                wrapper:{},
                                container:{},
                                content:{
                                    theme:{},
                                    predefined:{}
                                }
                            }),
                            error:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            label:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            description:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            checkbox:theme({
                                theme:{},
                                predefined:{
                                    bbackground:{
                                        dvalue:'c10504'
                                    },
                                    abackground:{
                                        dvalue:'c10504'
                                    },
                                    background:{
                                        dvalue:'c10503'
                                    },
                                    border:{
                                        dvalue:'c10503'
                                    }
                                }
                            })
                        }
                    }
                },
                invalid:{
                    type:"nested",
                    ___:{
                        nested:{
                            holder:holderTheme({
                                layer:{},
                                wrapper:{},
                                container:{},
                                content:{
                                    theme:{},
                                    predefined:{}
                                }
                            }),
                            error:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            label:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            description:theme({
                                theme:{},
                                predefined:{
                                    border:{},
                                    background:{}
                                }
                            }),
                            checkbox:theme({
                                theme:{},
                                predefined:{
                                    border:{
                                        dvalue:'c11008'
                                    }
                                }
                            })
                        }
                    }
                }
            }
        }
    },
    mapping:{
        type:"nested",
        ___:{
            nested:{
                labelElement:{
                    type:"enum",
                    dvalue:'wrapper',
                    ___:{
                        enum:{
                            options:"wrapper|container|content|layer|label|description"
                        }
                    }
                }
            }
        }
    },
    checkbox:{
        type:"nested",
        ___:{
            nested:{
                id:{
                    type:'string',
                },
                name:{
                    type:'string',
                },
                form:{
                    type:'string',
                },
                checked:bool(false),
                invalid:bool(false),
                disabled:bool(false),
                readonly:bool(false),
                required:bool(false),
                ds:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:null,
                                content:null,
                                ds:{
                                    ___:{
                                        nested:{
                                            theme:null,
                                            predefined:null,
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    radius:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:4
                                                                                },
                                                                                2:{
                                                                                    dvalue:4
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    holder:{
        type:'compProps',
        description:"",
        ___:{
            asroot:false,
            compProps:{
                from:'statics',
                mapping:'raw/atoms/layer-holder',
                overwirte:{
                    content:null,
                    templates:null,
                    layer:{
                        ___:{
                            nested:{
                                size:{
                                    dvalue:18
                                },
                                align:{
                                    dvalue:'tl'
                                }
                            }
                        }
                    },
                    config:{
                        ___:{
                            nested:{
                                layer:excludeTheme(),
                                content:excludeTheme({
                                    ___:{
                                        predefined:{
                                            overwirte:{
                                                spaceFromLayer:{
                                                    dvalue:12
                                                }
                                            }
                                        }
                                    }
                                }),
                                wrapper:excludeTheme(),
                                container:excludeTheme()
                            }
                        }
                    }
                }
            }
        }
    },
    callback:{
        type:"nested",
        description:"A callback function is a function passed from a parent component to a child component through props, allowing the child component to execute logic in the parent when a specific event occurs.",
        ___:{
            nested:{
                input:{
                    type:'nested',
                    ___:{
                        nested:{
                            onBlur:func(),
                            onClick:func(),
                            onFocus:func(),
                            onKeyUp:func(),
                            onChange:func(),
                            onKeyDown:func(),
                            onDragStart:func(),
                            onPointerUp:func(),
                            onMouseDown:func(),
                            onPointerDown:func(),
                            onPointerEnter:func(),
                            onPointerLeave:func()
                        }
                    }
                },
                label:{
                    type:'nested',
                    ___:{
                        nested:{
                            onClick:func(),
                            onKeyDown:func(),
                            onPointerUp:func(),
                            onMouseDown:func(),
                            onDragStart:func(),
                            onPointerDown:func(),
                            onPointerEnter:func(),
                            onPointerLeave:func()
                        }
                    }
                }
            }
        }
    }
}