import Radio from 'aio-global-raw-ui/atoms/form/radio';

export default {
	title:"Atoms/Form/Radio",
	argTypes:{

	},
	component:Radio,
	tags:['autodocs'],
	parameters:{
		layout:"centered",
		docs:{
			description:{
				component:"The Button component is a reusable React UI component designed to provide a consistent button experience across the application. It supports customizable content, styling, and optional icons on both the left and right sides of the button label.<br/><br/><strong>Import path:</strong><code>import Radio from 'aio-global-raw-ui/atoms/form/radio';</code><br/><br/><strong>Component directory:</strong><code>./libs/frontend/ui/raw/atoms/form/radio/index</code><br/><br/>"
			}
		}
	},
	mockdata:{
		defaults:{

		},
		variants:{

		}
	}
}

export const Base = {
	args:{
		label:{
			text:'',
			config:{
				markup:{
					element:"p"
				}
			}
		},
		error:{
			text:'',
			config:{
				markup:{
					element:"p"
				},
				ds:{
					css:{
						class:{
							fontsize:"xs",
							margin:{
								1:4,
								2:0,
								3:0
							}
						}
					}
				}
			}
		},
		description:{
			text:'',
			config:{
				markup:{
					element:"p"
				},
				ds:{
					css:{
						class:{
							fontsize:"xs",
							margin:{
								1:4,
								2:0,
								3:0
							}
						}
					}
				}
			}
		},
		theme:{
			default:{
				error:{
					predefined:{
						color:"c11008"
					}
				},
				checkbox:{
					predefined:{
						border:"c10503",
						background:"c00000"
					}
				}
			},
			checked:{
				checkbox:{
					predefined:{
						border:"c00207",
						background:"c00207",
						bbackground:"c00000"
					}
				}
			},
			disabled:{
				checkbox:{
					predefined:{
						border:"c10503",
						background:"c10503",
						abackground:"c10504",
						bbackground:"c10504"
					}
				}
			},
			invalid:{
				checkbox:{
					predefined:{
						border:"c11008"
					}
				}
			}
		},
		mapping:{
			labelElement:"wrapper"
		},
		checkbox:{
			checked:false,
			invalid:false,
			disabled:false,
			readonly:false,
			required:false,
			ds:{
				ds:{
					css:{
						class:{
							radius:{
								1:4,
								2:4
							}
						}
					}
				}
			}
		},
		holder:{
			wrap:false,
			layer:{
				align:"tl",
				size:18,
				dimensions:{
					width:'',
					height:''
				}
			},
			config:{
				wrapper:{
					markup:{
						element:"div"
					}
				},
				container:{
					markup:{
						element:"div"
					}
				},
				content:{
					markup:{
						element:"div"
					},
					spaceFromLayer:12
				},
				layer:{
					markup:{
						element:"div"
					}
				}
			}
		},
		callback:{
			input:{
				onBlur:null,
				onClick:null,
				onFocus:null,
				onKeyUp:null,
				onChange:null,
				onKeyDown:null,
				onDragStart:null,
				onPointerUp:null,
				onMouseDown:null,
				onPointerDown:null,
				onPointerEnter:null,
				onPointerLeave:null
			},
			label:{
				onClick:null,
				onKeyDown:null,
				onPointerUp:null,
				onMouseDown:null,
				onDragStart:null,
				onPointerDown:null,
				onPointerEnter:null,
				onPointerLeave:null
			}
		}
	}
}