const helpers = process.uiHelpers();
const avatar = process.aioAppConfigs('storybook/raw/atoms/avatar/icon');

module.exports = helpers.json.merge(helpers.json.get(avatar, 'props', {}), {
    nowrapper:{
        dvalue:false
    },
    dsTheme:{
        ___:{
            predefined:{
                overwirte:{
                    radius:{
                        dvalue:'round'
                    },
                    border:{
                        dvalue:'c00103'
                    },
                    background:{
                        dvalue:'c00102'
                    },
                }
            }
        }
    },
    icon:{
        ___:{
            compProps:{
                overwirte:{
                    config:{
                        ___:{
                            predefined:{
                                overwirte:{
                                    svg:{
                                        ___:{
                                            nested:{
                                                size:{
                                                    dvalue:'18px'
                                                }
                                            }
                                        }
                                    },
                                    icon:{
                                        ___:{
                                            nested:{
                                                size:{
                                                    dvalue:'18'
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    config:{
        ___:{
            nested:{
                wrapper:{
                    ___:{
                        predefined:{
                            overwirte:{
                                content:null,
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                },
                                ds:{
                                    ___:{
                                        nested:{
                                            css:{
                                                ___:{
                                                    nested:{ 
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    padding:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:6
                                                                                },
                                                                                2:{
                                                                                    dvalue:6
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }  
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
});