const schema = {
    "city":true,
    "name":true,
    "line1":true,
    "line2":true,
    "state":true,
    "mapId":true,
    "hashId":true,
    "country":true,
    "pincode":true,
    "nameHash":true,
    "landmark":true,
}

const update = () => {
    return {...schema}
}

module.exports = {
    response:{
        exclude:{
            enable:true,
            kies:{
                ts:true,
                typeHash:true
            }
        },
        transform:{
            enable:true,
            kies:{
                _id:"id"
            }
        }
    },
    valuemap:{},

    md5Hash:{
        hashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"number",
                    from:"random"
                }
            }
        },
        nameHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"name",
                    from:"body-item"
                }
            }
        }
    },

    schema:{
        default:schema,
        update:update()
    },

    signature:{
        merge:{
            enable:true
        },
        creation:{
            enable:true,
            nodes:{
                _id:{
                    enable:true,
                    valueType:"objectId"
                },
                _merchantId:{
                    enable:true,
                    valueType:"objectId"
                }
            }
        }
    },

    query:{
        byId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"_id",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        byMapId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"mapId",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
    }
}