const schema = {
    "collection":{
        "name":"ApiSchemas"
    },
    "schema":{
        "details":{
            "type":"nested",
            "schema":{
                "mapId":{
                    "type":'objectId',
                    "configs":{
                        "required":true,
                    }
                },
                "name":{
                    "type":'string',
                    "configs":{
                        "required":true,
                    }
                },
                "type":{
                    "type":'string',
                    "configs":{
                        "required":true,
                        "uppercase":true,
                        "enum":['CONTROLLER', 'VERSION', 'ACTION', 'METHOD', 'JOB']
                    }
                }
            }
        },
        "config":{
            "type":"nested",
            "schema":{
                "create":{
                    "type":"nested",
                    "schema":{
                        "config":{
                            "type":"nested",
                            "schema":{
                                "enable":{
                                    "type":"boolean",
                                    "configs":{
                                        "default":false
                                    }
                                }
                            }
                        },
                        "validation":{
                            "type":"nested",
                            "schema":{
                                "cookies":{
                                    "type":"object",
                                    "configs":{
                                        "default":{}
                                    }
                                },
                                "headers":{
                                    "type":"object",
                                    "configs":{
                                        "default":{}
                                    }
                                },
                                "body":{
                                    "type":"object",
                                    "configs":{
                                        "default":{}
                                    }
                                },
                                "params":{
                                    "type":"object",
                                    "configs":{
                                        "default":{}
                                    }
                                },
                                "query":{
                                    "type":"object",
                                    "configs":{
                                        "default":{}
                                    }
                                }
                            }
                        }
                    }
                },
                "update":{
                    "type":"nested",
                    "schema":{
                        "config":{
                            "type":"nested",
                            "schema":{
                                "enable":{
                                    "type":"boolean",
                                    "default":false
                                }
                            }
                        }
                    }
                },
                "common":{
                    "type":"nested",
                    "schema":{
                        "request":{
                            "type":"nested",
                            "schema":{
                                "auth":{
                                    "type":"nested",
                                    "schema":{
                                        "type":{
                                            "type":'string',
                                            "configs":{
                                                "required":true,
                                                "uppercase":true,
                                                "enum":["PUBLIC", "S2S", "PARTNER"]
                                            }
                                        },
                                        "sso":{
                                            "type":'string',
                                            "configs":{
                                                "required":true,
                                                "enum":["required", "optional"]
                                            }
                                        }
                                    }
                                },
                                "body":{
                                    "type":"nested",
                                    "schema":{
                                        "min":{
                                            "type":'number',
                                        },
                                        "max":{
                                            "type":'number',
                                        },
                                        "type":{
                                            "type":'string',
                                            "configs":{
                                                "required":true,
                                                "enum":["list", "object"]
                                            }
                                        }, // List or Object
                                        "required":{
                                            "type":'string',
                                            "configs":{
                                                "required":true,
                                                "enum":["required", "optional"]
                                            }
                                        },
                                        "message":{
                                            "type":"nested",
                                            "schema":{
                                                "error":{
                                                    "type":"paragraph",
                                                    "configs":{
                                                    }
                                                },
                                                "success":{
                                                    "type":"paragraph",
                                                    "configs":{
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "methods":{
                                    "type":"nested",
                                    "schema":{
                                        "put":{
                                            "type":"nested",
                                            "schema":{
                                                "allowed":{
                                                    "type":"boolean",
                                                     "default":false
                                                },
                                                "message":{
                                                    "type":"nested",
                                                    "schema":{
                                                        "error":{
                                                            "type":"paragraph",
                                                            "configs":{
                                                            }
                                                        },
                                                        "success":{
                                                            "type":"paragraph",
                                                            "configs":{
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "get":{
                                            "type":"nested",
                                            "schema":{
                                                "allowed":{
                                                    "type":"boolean",
                                                     "default":false
                                                },
                                                "message":{
                                                    "type":"nested",
                                                    "schema":{
                                                        "error":{
                                                            "type":"paragraph",
                                                            "configs":{
                                                            }
                                                        },
                                                        "success":{
                                                            "type":"paragraph",
                                                            "configs":{
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "post":{
                                            "type":"nested",
                                            "schema":{
                                                "allowed":{
                                                    "type":"boolean",
                                                     "default":false
                                                },
                                                "message":{
                                                    "type":"nested",
                                                    "schema":{
                                                        "error":{
                                                            "type":"paragraph",
                                                            "configs":{
                                                            }
                                                        },
                                                        "success":{
                                                            "type":"paragraph",
                                                            "configs":{
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "delete":{
                                            "type":"nested",
                                            "schema":{
                                                "allowed":{
                                                    "type":"boolean",
                                                     "default":false
                                                },
                                                "message":{
                                                    "type":"nested",
                                                    "schema":{
                                                        "error":{
                                                            "type":"paragraph",
                                                            "configs":{
                                                            }
                                                        },
                                                        "success":{
                                                            "type":"paragraph",
                                                            "configs":{
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

module.exports = schema;