import ContentRow from 'aio-global-raw-ui/atoms/content-row';

export default {
	title:"Atoms/ContentRow",
	argTypes:{

	},
	component:ContentRow,
	tags:['autodocs'],
	parameters:{
		layout:"centered",
		docs:{
			description:{
				component:"ContentRow is a reusable layout component that divides content into five distinct sections: start, before, center, after, and end. Parent components can pass dynamic child elements as props, which are rendered in their respective sections. This flexible structure enables developers to customize the layout while maintaining consistency across the application, making the component highly reusable for a variety of UI scenarios.<br/><br/><strong>Import path:</strong><code>import ContentRow from 'aio-global-raw-ui/atoms/content-row';</code><br/><br/><strong>Component directory:</strong><code>./libs/frontend/ui/raw/atoms/content-row/index</code><br/><br/>"
			}
		}
	},
	mockdata:{
		defaults:{
			childs:{
				start:"Start",
				before:"Before",
				center:"Center",
				end:"End",
				after:"After"
			},
			config:{
				wrapper:{
					ds:{
						predefined:{
							background:"c00204"
						},
						css:{
							class:{
								padding:{
									1:10,
									2:10,
									3:10,
									4:10
								},
								radius:{
									1:6,
									2:6
								}
							}
						}
					}
				},
				start:{
					ds:{
						predefined:{
							background:"c11605"
						},
						css:{
							class:{
								margin:{
									1:0,
									2:6,
									3:0,
									4:0
								},
								padding:{
									1:6,
									2:6
								},
								radius:{
									1:6,
									2:6
								}
							}
						}
					}
				},
				before:{
					ds:{
						predefined:{
							background:"c11805"
						},
						css:{
							class:{
								margin:{
									1:0,
									2:10
								},
								padding:{
									1:10,
									2:10
								},
								radius:{
									1:6,
									2:6
								}
							}
						}
					}
				},
				center:{
					ds:{
						predefined:{
							background:"c12106"
						},
						css:{
							class:{
								margin:{
									1:0,
									2:10
								},
								padding:{
									1:10,
									2:10
								},
								radius:{
									1:6,
									2:6
								}
							}
						}
					}
				},
				after:{
					ds:{
						predefined:{
							background:"c11906"
						},
						css:{
							class:{
								margin:{
									1:0,
									2:10
								},
								padding:{
									1:10,
									2:10
								},
								radius:{
									1:6,
									2:6
								}
							}
						}
					}
				},
				end:{
					ds:{
						predefined:{
							background:"c10806"
						},
						css:{
							class:{
								margin:{
									1:0,
									2:10
								},
								padding:{
									1:10,
									2:10
								},
								radius:{
									1:6,
									2:6
								}
							}
						}
					}
				}
			}
		},
		variants:{

		}
	}
}

export const Base = {
	args:{
		callbacks:{
			onClick:null,
			onBlur:null,
			onFocus:null,
			onKeyUp:null,
			dsTheme:null,
			onKeyDown:null,
			onDragStart:null,
			onMouseDown:null,
			onPointerUp:null,
			onPointerDown:null,
			onPointerEnter:null,
			onPointerLeave:null,
			beforeRender:null
		},
		childs:{
			start:"Start",
			before:"Before",
			center:"Center",
			end:"End",
			after:"After"
		},
		config:{
			center:{
				markup:{
					element:"div"
				},
				ds:{
					predefined:{
						background:"c12106"
					},
					css:{
						class:{
							margin:{
								1:0,
								2:10
							},
							padding:{
								1:10,
								2:10
							},
							radius:{
								1:6,
								2:6
							}
						}
					}
				}
			},
			wrapper:{
				markup:{
					element:"div"
				},
				ds:{
					predefined:{
						background:"c00204"
					},
					css:{
						class:{
							padding:{
								1:10,
								2:10,
								3:10,
								4:10
							},
							radius:{
								1:6,
								2:6
							}
						}
					}
				}
			},
			end:{
				markup:{
					element:"div"
				},
				ds:{
					predefined:{
						background:"c10806"
					},
					css:{
						class:{
							margin:{
								1:0,
								2:10
							},
							padding:{
								1:10,
								2:10
							},
							radius:{
								1:6,
								2:6
							}
						}
					}
				}
			},
			after:{
				markup:{
					element:"div"
				},
				ds:{
					predefined:{
						background:"c11906"
					},
					css:{
						class:{
							margin:{
								1:0,
								2:10
							},
							padding:{
								1:10,
								2:10
							},
							radius:{
								1:6,
								2:6
							}
						}
					}
				}
			},
			start:{
				markup:{
					element:"div"
				},
				ds:{
					predefined:{
						background:"c11605"
					},
					css:{
						class:{
							margin:{
								1:0,
								2:6,
								3:0,
								4:0
							},
							padding:{
								1:6,
								2:6
							},
							radius:{
								1:6,
								2:6
							}
						}
					}
				}
			},
			before:{
				markup:{
					element:"div"
				},
				ds:{
					predefined:{
						background:"c11805"
					},
					css:{
						class:{
							margin:{
								1:0,
								2:10
							},
							padding:{
								1:10,
								2:10
							},
							radius:{
								1:6,
								2:6
							}
						}
					}
				}
			}
		}
	}
}