const helpers = process.uiHelpers();
const icon = process.aioAppConfigs('storybook/raw/atoms/icons');

const predefined = (arg) => {
    return helpers.json.merge({
        from:'statics',
        mapping:'ds.configs',
        overwirte:{
            markup:null,
            ds:{
                ___:{
                    nested:{
                        predefined:{
                            ___:{
                                predefined:{
                                    overwirte:{
                                        background:{}
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }, arg || {});
}

const dsConfig = (arg) => {
    return {
        type:'predefined',
        description:"The configuration supports design system–driven customization across various elements, including the avatar image, wrapper, and initials. Properties such as size, shape, border, background color, and typography can be configured through the design system, ensuring visual consistency, accessibility, and alignment with application design standards across different themes and use cases.",
        ___:{
            predefined:predefined(arg)
        }
    }
}


module.exports = {
    callbacks:{
        type:'nested',
        description:'',
        ___:{
            nested:{
                onClose:{
                    dvalue:null,
                    type:'function',
                    descripttion:''
                },
                onOpen:{
                    dvalue:null,
                    type:'function',
                    descripttion:''
                },
            }
        }
    },
    templates:{
        type:'nested',
        description:'',
        ___:{
            nested:{
                title:{
                    dvalue:null,
                    type:'function',
                    descripttion:''
                },
                body:{
                    dvalue:null,
                    type:'function',
                    descripttion:''
                }
            }
        }
    },
    id:{
        type:'string',
        description:''
    },
    active:{
        dvalue:true,
        type:'boolean',
        description:''
    },
    hideClose:{
        dvalue:false,
        type:'boolean',
        description:''
    },
    bindJsComponents:{
        dvalue:true,
        type:'boolean',
         description:''
    },
    backdropClose:{
        dvalue:true,
        type:'boolean',
        description:''
    },
    pageview:{
        dvalue:false,
        type:'boolean',
        description:''
    },
    direction:{
        type:"enum",
        dvalue:'right',
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"slideDrawer.directions"
            }
        }
    },
    closeIcon:{
        type:'nested',
        ___:{
            nested:helpers.json.merge(helpers.json.get(icon, 'props', {}), {
                config:{
                    ___:{
                        predefined:{
                            overwirte:{
                                svg:{
                                    ___:{
                                        nested:{
                                            size:{
                                                dvalue:'16px'
                                            }
                                        }
                                    }
                                },
                                icon:{
                                    ___:{
                                        nested:{
                                            name:{
                                                dvalue:'close'
                                            },
                                            size:{
                                                dvalue:'16'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            })
        }
    },
    configs:{
        type:'nested',
        ___:{
            nested:{
                wrapper:dsConfig(),
                contentWrapper:dsConfig({
                    overwirte:{
                        markup:null,
                        ds:{
                            ___:{
                                nested:{
                                    predefined:{
                                        ___:{
                                            predefined:{
                                                overwirte:{
                                                    background:{
                                                        dvalue:'c00000'
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }),
                titleWrapper:dsConfig({
                    overwirte:{
                        markup:{
                            ___:{
                                nested:{
                                    element:{
                                        dvalue:'div'
                                    }
                                }
                            }
                        },
                        ds:{
                            ___:{
                                nested:{
                                    predefined:{
                                        ___:{
                                            predefined:{
                                                overwirte:{
                                                    border:{
                                                        dvalue:''
                                                    },
                                                    background:{
                                                        dvalue:''
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    css:{
                                        ___:{
                                            nested:{
                                                class:{
                                                    ___:{
                                                        nested:{
                                                            family:{
                                                                dvalue:'md'
                                                            },
                                                            fontsize:{
                                                                dvalue:'lg'
                                                            },
                                                            border:{
                                                                dvalue:1
                                                            },
                                                            borderNone:{
                                                                ___:{
                                                                    nested:{
                                                                        1:{
                                                                            dvalue:true
                                                                        }, 
                                                                        2:{
                                                                            dvalue:true
                                                                        },
                                                                        3:{
                                                                            dvalue:false
                                                                        },
                                                                        4:{
                                                                            dvalue:true
                                                                        }
                                                                    }
                                                                }
                                                            },
                                                            padding:{
                                                                ___:{
                                                                    nested:{
                                                                        1:{
                                                                            dvalue:10
                                                                        },
                                                                        2:{
                                                                            dvalue:18
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }),
                bodyWrapper:dsConfig({
                    overwirte:{
                        markup:{
                            ___:{
                                nested:{
                                    element:{
                                        dvalue:'div'
                                    }
                                }
                            }
                        },
                        ds:{
                            ___:{
                                nested:{
                                    predefined:{
                                        ___:{
                                            predefined:{
                                                overwirte:{
                                                    background:{
                                                        dvalue:''
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    css:{
                                        ___:{
                                            nested:{
                                                class:{
                                                    ___:{
                                                        nested:{
                                                            padding:{
                                                                ___:{
                                                                    nested:{
                                                                        1:{
                                                                            dvalue:12
                                                                        },
                                                                        2:{
                                                                            dvalue:16
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }),
                contentBody:dsConfig({
                    overwirte:{
                        ds:{
                            ___:{
                                nested:{
                                    predefined:{
                                        ___:{
                                            predefined:{
                                                overwirte:{
                                                    background:{
                                                        dvalue:''
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }),
                closeIconWrapper:dsConfig({
                    overwirte:{
                        ds:{
                            ___:{
                                nested:{
                                    predefined:{
                                        ___:{
                                            predefined:{
                                                overwirte:{
                                                    color:{
                                                        dvalue:'c00000'
                                                    },
                                                    hcolor:{
                                                        dvalue:'c00000'
                                                    },
                                                    background:{
                                                        dvalue:''
                                                    },
                                                    hbackground:{
                                                        dvalue:'c00000'
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    css:{
                                        ___:{
                                            nested:{
                                                class:{
                                                    ___:{
                                                        nested:{
                                                            padding:{
                                                                ___:{
                                                                    nested:{
                                                                        1:{
                                                                            dvalue:6
                                                                        },
                                                                        2:{
                                                                            dvalue:6
                                                                        },
                                                                        3:{
                                                                            dvalue:4
                                                                        },
                                                                        4:{
                                                                            dvalue:6
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                })
            }
        }
    }
}