module.exports = {
    bindJsComponents:{
        type:"boolean",
        dvalue:true,
        description:"Determines whether the Read More/Read Less JavaScript bindings are applied to the component. Enable this option when the component is rendered as static server-generated HTML and requires client-side behavior to be initialized in the browser."
    },
    wrapper:{
        type:'predefined',
        description:"",
        ___:{
            predefined:{
                from:'statics',
                mapping:'ds.configs',
                overwirte:{
                    content:null,
                    markup:{
                        type:'nested',
                        ___:{
                            nested:{
                                element:{
                                    dvalue:'div'
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    description:{
        type:'compProps',
        description:"Contains the configuration-to-props mapping for the component. Values defined here are transformed into component props and applied when the component is rendered.",
        ___:{
            compProps:{
                from:'statics',
                mapping:'raw/atoms/typography/text',
            }
        }
    },
    toggle:{
        type:'nested',
        description:"Default text",
        ___:{
            nested:{
                lines:{
                    type:'number',
                    dvalue:5
                },
                enabled:{
                    type:"boolean",
                    dvalue:false,
                },
                align:{
                    type:'enum',
                    dvalue:'al',
                    description:"",
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:"global.text.align"
                        }
                    }
                },
                label:{
                    type:'nested',
                    ___:{
                        nested:{
                            more:{
                                type:'string',
                                dvalue:'Read more'
                            },
                            less:{
                                type:'string',
                                dvalue:'Read less'
                            }
                        }
                    }
                },
                ds:{
                    type:'predefined',
                    description:"",
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                content:null,
                                markup:{
                                    type:'nested',
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'span'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}