module.exports = {
    size:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.size"
            }
        }
    },
    theme:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"button.theme"
            }
        }
    },

    radius:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.radius"
            }
        }
    },
    shadow:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.shadow"
            }
        }
    },
    color:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    border:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    pairing:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.pairing"
            }
        }
    },
    background:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    hcolor:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    hborder:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    hpairing:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    hbackground:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    acolor:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    bcolor:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    aborder:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    bborder:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    abackground:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    bbackground:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    hacolor:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    hbcolor:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    haborder:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    hbborder:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    habackground:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    },
    hbbackground:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.color"
            }
        }
    }, 
    font__d__size:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.font.size"
            }
        }
    },
    font__d__family:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.font.family"
            }
        }
    },
    font__d__heading:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.font.heading"
            }
        }
    },
    image__d__thumbnail:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.image.thumbnail"
            }
        }
    },
    width:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.height"
            }
        }
    },
    height:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.height"
            }
        }
    },
    minWidth:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.height"
            }
        }
    },
    minHeight:{
        type:"enum",
        description:"",
        ___:{
            enum:{
                from:'statics',
                mapping:"global.height"
            }
        }
    },
    className:{
        type:"string",
        description:"",
    }
}