const helpers = process.uiHelpers();
const accordion = process.aioAppConfigs('storybook/raw/atoms/accordion/group');
const storybook = {
    predefined:process.aioAppConfigs('storybook/predefined')
}

const headerProps = () => {
    return {
        ___:{
            nested:{
                expendIcon:{
                    ___:{
                        nested:{
                            placement:{
                                dvalue:'start'
                            },
                            names:{
                                ___:{
                                    nested:{
                                        selected:{
                                            dvalue:'minus'
                                        },
                                        default:{
                                            dvalue:'plus'
                                        }
                                    }
                                }
                            },
                            config:{
                                type:'nested',
                                ___:{
                                    nested:{
                                        config:{
                                            ___:{
                                                predefined:{
                                                    overwirte:{
                                                        svg:{
                                                            ___:{
                                                                nested:{
                                                                    size:{
                                                                        dvalue:'20px'
                                                                    }
                                                                }
                                                            }
                                                        },
                                                        icon:{
                                                            ___:{
                                                                nested:{
                                                                    size:{
                                                                        dvalue:'20'
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                config:{
                    ___:{
                        nested:{
                            start:{
                                ___:{
                                    predefined:{
                                        overwirte:{
                                            ds:{
                                                ___:{
                                                    nested:{
                                                        css:{
                                                            ___:{
                                                                nested:{
                                                                    class:{
                                                                        ___:{
                                                                            nested:{
                                                                                margin:{
                                                                                    ___:{
                                                                                        nested:{
                                                                                            1:{
                                                                                                dvalue:0
                                                                                            },
                                                                                            2:{
                                                                                                dvalue:10
                                                                                            },
                                                                                            3:{
                                                                                                dvalue:0
                                                                                            },
                                                                                            4:{
                                                                                                dvalue:0
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            end:{
                                ___:{
                                    predefined:{
                                        overwirte:{
                                            ds:{
                                                ___:{
                                                    nested:{
                                                        css:{
                                                            ___:{
                                                                nested:{
                                                                    class:{
                                                                        ___:{
                                                                            nested:{
                                                                                margin:{
                                                                                    ___:{
                                                                                        nested:{
                                                                                            1:{
                                                                                                dvalue:''
                                                                                            },
                                                                                            2:{
                                                                                                dvalue:''
                                                                                            },
                                                                                            3:{
                                                                                                dvalue:''
                                                                                            },
                                                                                            4:{
                                                                                                dvalue:''
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

const body = () => {
    return {
        ___:{
            nested:{
                wrapper:{
                    ___:{
                        predefined:{ 
                            overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    fontsize:{
                                                                        dvalue:'md'
                                                                    },
                                                                    padding:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:0
                                                                                },
                                                                                2:{
                                                                                    dvalue:6
                                                                                },
                                                                                3:{
                                                                                    dvalue:0
                                                                                },
                                                                                4:{
                                                                                    dvalue:6
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        },
                                                        flags:{
                                                            ___:{
                                                                nested:{
                                                                    animation:{
                                                                        dvalue:'anim'
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

module.exports = helpers.json.merge(helpers.json.get(accordion, 'props', {}), {
    item:{
        ___:{
            nested:{
                body:body(),
                header:headerProps()
            }
        }
    },
    mapping:{
        ___:{
            nested:{
                tree:{
                    type:'nested',
                    ___:{
                        nested:{
                            childs:{
                                type:'string',
                                description:'',
                                dvalue:'childs'
                            }
                        }
                    }
                }
            }
        }
    },
    expended:{
        dvalue:false,
        type:'boolean',
        description:'Default expended'
    },
    templates:{
        ___:{
            nested:{
                treeList:{
                    type:'nested',
                    ___:{
                        nested:{
                            render:{
                                dvalue:null,
                                type:'function',
                                descripttion:''
                            }
                        }
                    }
                }
            }
        }
    }
});