module.exports = {
    masterData:{
        rootMasterData:'/api/irms/orgMasterData/details/v1/root/fetch'
    },

    access:{
        map:{
            create:"/api/irms/accessMap/details/v1/info/create",
            update:"/api/irms/accessMap/details/v1/infoById/update/:_id_:",
            getById:"/api/irms/accessMap/details/v1/getById/fetch/:_id_:",
            getByMapId:"/api/irms/accessMap/details/v1/getByMapId/fetch/:_id_:",
            getByMapIdAndType:"/api/irms/accessMap/details/v1/getByMapIdAndType/fetch/:_id_:/:_type_:"
        },
        role:{
            create:"/api/irms/accessRole/details/v1/info/create",
            update:"/api/irms/accessRole/details/v1/infoById/update/:_id_:",
            getById:"/api/irms/accessRole/details/v1/getById/fetch/:_id_:",
            getByMapId:"/api/irms/accessRole/details/v1/getByMapId/fetch/:_id_:"
        },
        preset:{
            create:"/api/irms/accessPreset/details/v1/info/create",
            update:"/api/irms/accessPreset/details/v1/infoById/update/:_id_:",
            getById:"/api/irms/accessPreset/details/v1/getById/fetch/:_id_:",
            getByMapId:"/api/irms/accessPreset/details/v1/getByMapId/fetch/:_id_:"
        },
        permission:{
            create:"/api/irms/permission/details/v1/info/create"
        }
    },

    common:{
        roles:{
            create:"/api/irms/roles/details/v1/info/create",
            update:"/api/irms/roles/details/v1/infoById/update/:_id_:",
            detailsById:"/api/irms/roles/details/v1/getRoleById/fetch/:_id_:",
            byDepatmentId:"/api/irms/roles/details/v1/getRoleByDepartmentId/fetch/:_id_:"
        },
        departments:{
            createRoot:'/api/irms/departments/details/v1/root/create',
            createChild:'/api/irms/departments/details/v1/child/create',
            createInfo:'/api/irms/departments/details/v1/info/create',
            updateRoot:'/api/irms/departments/details/v1/root/update/:_id_:',
            updateChild:'/api/irms/departments/details/v1/child/update/:_id_:',
            updateInfo:'/api/irms/departments/details/v1/info/update/:_id_:',
            detailsById:"/api/irms/departments/details/v1/getById/fetch/:_id_:",
            getChildsByParentId:'/api/irms/departments/details/v1/getChildsByParentId/fetch/:_id_:',
        },
        eat:{
            createRoot:'/api/irms/eat/details/v1/root/create',
            createChild:'/api/irms/eat/details/v1/child/create',
            createInfo:'/api/irms/eat/details/v1/info/create',
            updateRoot:'/api/irms/eat/details/v1/root/update/:_id_:',
            updateChild:'/api/irms/eat/details/v1/child/update/:_id_:',
            updateInfo:'/api/irms/eat/details/v1/info/update/:_id_:',
            detailsById:'/api/irms/eat/details/v1/getById/fetch/:_id_:',
            listByParentId:'/api/irms/eat/details/v1/getChildsByParentId/fetch/:_id_:'
        },
        ars:{
            create:'/api/irms/ar/details/v1/info/create',
            update:'/api/irms/ar/details/v1/byId/update/:_id_:',
            detailsById:'/api/irms/ar/details/v1/byId/fetch/:_id_:',
            listByMapId:'/api/irms/ar/details/v1/byMapId/fetch/:_id_:'
        },
        rbas:{
            create:'/api/irms/rba/details/v1/info/create',
            update:'/api/irms/rba/details/v1/byId/update/:_id_:',
            detailsById:'/api/irms/rba/details/v1/byId/fetch/:_id_:',
            listByMapId:'/api/irms/rba/details/v1/byMapId/fetch/:_id_:',
            listByMapIdAndLinkFor:"/api/irms/rba/details/v1/byMapIdAndLinkFor/fetch/:_id_:/:_linkFor_:"
        },
        ibps:{
            create:'/api/irms/ibp/details/v1/info/create',
            update:'/api/irms/ibp/details/v1/byId/update/:_id_:',
            detailsById:'/api/irms/ibp/details/v1/byId/fetch/:_id_:',
            listByItemId:'/api/irms/ibp/details/v1/byItemId/fetch/:_id_:'
        },
        tbis:{
            create:'/api/irms/tbi/details/v1/info/create',
            update:'/api/irms/tbi/details/v1/byId/update/:_id_:',
            detailsById:'/api/irms/tbi/details/v1/byId/fetch/:_id_:',
            byItemIdAndType:'/api/irms/tbi/details/v1/byItemIdAndType/fetch/:_id_:/:_type_:'
        },
        tbus:{
            create:'/api/irms/tbu/details/v1/info/create',
            update:'/api/irms/tbu/details/v1/byId/update/:_id_:',
            detailsById:'/api/irms/tbu/details/v1/byId/fetch/:_id_:',
            listByTeamId:'/api/irms/tbu/details/v1/byTeamId/fetch/:_id_:'
        },
        tbmbr:{
            create:'/api/irms/tbmbr/details/v1/info/create',
            update:'/api/irms/tbmbr/details/v1/byId/update/:_id_:',
            detailsById:'/api/irms/tbmbr/details/v1/byId/fetch/:_id_:',
            listByTeamId:'/api/irms/tbmbr/details/v1/byTeamId/fetch/:_id_:'
        },
        bus:{
            create:"/api/irms/businessUnit/details/v1/info/create",
            update:"/api/irms/businessUnit/details/v1/updateById/update/:_id_:",
            rootList:'/api/irms/businessUnit/list/v1/listByEmployerId/fetch/:_id_:',
            detailsById:"/api/irms/businessUnit/details/v1/byId/fetch/:_id_:"
        },
        bvs:{
            createRoot:'/api/irms/businessVerticals/details/v1/root/create',
            createChild:'/api/irms/businessVerticals/details/v1/child/create',
            createInfo:'/api/irms/businessVerticals/details/v1/info/create',
            updateRoot:'/api/irms/businessVerticals/details/v1/root/update/:_id_:',
            updateChild:'/api/irms/businessVerticals/details/v1/child/update/:_id_:',
            updateInfo:'/api/irms/businessVerticals/details/v1/info/update/:_id_:',
            detailsByHashId:"/api/irms/businessVerticals/details/v1/getByHashId/fetch/:_id_:",
            listByParentId:'/api/irms/businessVerticals/details/v1/getChildsByParentId/fetch/:_id_:',
        },
        offices:{
            create:"/api/irms/officeAdd/details/v1/info/create",
            update:"/api/irms/officeAdd/details/v1/updateById/update/:_id_:",
            byEmployerId:'/api/irms/officeAdd/list/v1/byEmployer/fetch/:_id_:',
            detailsById:"/api/irms/officeAdd/details/v1/byId/fetch/:_id_:"
        },
        team:{
            create:"/api/irms/team/details/v1/info/create",
            update:"/api/irms/team/details/v1/infoById/update/:_id_:",
            detailsById:"/api/irms/team/details/v1/getById/fetch/:_id_:",
            listByTypeAndMapId:"/api/irms/team/details/v1/getByMapIdAndType/fetch/:_mapId_:/:_type_:"
        }
    },

    group:{},

    org:{
        offices:{
            create:"/api/irms/officeAdd/details/v1/info/create",
            update:"/api/irms/officeAdd/details/v1/updateById/update/:_id_:",
            rootList:'/api/irms/officeAdd/list/v1/byEmployer/fetch/:_id_:',
            detailsById:"/api/irms/officeAdd/details/v1/byId/fetch/:_id_:"
        },
        employers:{
            create:"/api/irms/employer/details/v1/info/create",
            update:"/api/irms/employer/details/v1/updateById/update/:_id_:",
            rootList:'/api/irms/employer/list/v1/byMerchant/fetch',
            detailsById:"/api/irms/employer/details/v1/byId/fetch/:_id_:"
        }
    },

    employee:{
        account:{
            create:'/api/irms/emps/account/v1/details/create',
            createPassword:'/api/irms/emps/login/v1/fpwd/create/email/otp'
        },
        directory:{
            listByMerchant:"/api/irms/empInfo/profile/v1/allByMerchant/fetch",
            personalInfoByMapId:'/api/irms/empInfo/personal/v1/detailsByMapId/fetch/:_id_:'
        },
        profile:{
            detailsByMapId:"/api/irms/empInfo/profile/v1/allDetailsByMapId/fetch/:_id_:",
            updatePersonalDetailsByMapId:"/api/irms/empInfo/personal/v1/detailsByMapId/update/:_id_:"
        },
        employementInfo:{
            create:"/api/irms/employmentInfo/details/v1/byMapId/create",
            update:"/api/irms/employmentInfo/details/v1/byMapId/update/:_id_:",
            getByMapId:'/api/irms/employmentInfo/details/v1/byMapId/fetch/:_id_:'
        },

        empTeams:{
            getByIdAndType:'/api/irms/empTeam/details/v1/getByEmpIdAndType/fetch/:_id_:/:_subId_:',
        }
    },

    auth:{
        session:{
            login:'/api/irms/emps/login/v1/session/create/email/password'
        },
        account:{
            createPassword:'/api/irms/emps/login/v1/cpwd/create',
            sendOtpOnEmailToCreatePassword:'/api/irms/emps/login/v1/fpwd/create/email/otp',
        }
    },

    tdc:{
        app:{
            createUiApp:"/api/irms/app/details/v1/ui/create",
            createApiApp:"/api/irms/app/details/v1/api/create",
            listByCate:"/api/irms/app/list/v1/byCate/fetch/:_cate_:",
            getById:"/api/irms/app/details/v1/getById/fetch/:_id_:",
            updateUiAppById:"/api/irms/app/details/v1/ui/update/:_id_:",
            updateApiAppById:"/api/irms/app/details/v1/api/update/:_id_:"
        }
    }
}