const schema = {
    "code":true,
    "name":true,
    "type":true,
    "mapId":true,
    "hashId":true,
    "nameHash":true,
    "codeHash":true,
    "typeHash":true,
    "hasChilds":true,
    "description":true,
}

const update = () => {
    return {...schema, ...{hashId:false, mapId:false, type:false}}
}

module.exports = {
    response:{
        exclude:{
            enable:true,
            kies:{
                ts:true,
                nameHash:true,
                isAccessControlled:true
            }
        },
    },
    valuemap: {},

    md5Hash:{
        hashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"number",
                    from:"random"
                }
            }
        },
        nameHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"name",
                    from:"body-item"
                }
            }
        },
        codeHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"code",
                    from:"body-item"
                }
            }
        },
        typeHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"mapId",
                    from:"body-item"
                },
                2:{
                    map:"code",
                    from:"body-item"
                },
                3:{
                    map:"type",
                    from:"body-item"
                }
            }
        }
    },

    schema:{
        default:schema,
        update:update()
    },

    signature:{
        merge:{
            enable:true
        },
        creation:{
            enable:true,
            nodes:{
                _id:{
                    enable:true,
                    valueType:"objectId"
                },
                _merchantId:{
                    enable:true,
                    valueType:"objectId"
                }
            }
        }
    },

    query:{
        byId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"_id",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        mapId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"mapId",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        mapIdAndType:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"mapId",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        },
                        1:{
                            cloumn:"type",
                            value:{
                                map:"subId",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        byMerchantAndType:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        1:{
                            cloumn:"type",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    validation:{
        errors:{
            nameHash:{
                mapTo:'name',
                messages:{
                    11000:'Duplicate name is not allowed'
                }
            }, 
            typeHash:{
                mapTo:'type',
                messages:{
                    11000:'Duplicate type is not allowed'
                }
            },
            codeHash:{
                mapTo:'code',
                messages:{
                    11000:'Duplicate code is not allowed'
                }
            }
        }
    },

    values:{
        infoDetails:{
            default:{},
            exclude:{},
            hardcoded:{},
        }
    }
}