module.exports = {
    "button":{
        "prefix":"btn",
        "disabled":"0"
    },
    "input":{
        "prefix":"inpt",
        "disabled":"0"
    },



    "dot":{
        "prefix":"dot",
        "disabled":"0"
    },
    "list":{
        "prefix":"list",
        "disabled":"0"
    },
    "blank":{
        "prefix":"blank",
        "disabled":"0"
    },
    "chip":{
        "prefix":"chip",
        "disabled":"0"
    },
    "grid":{
        "prefix":"grid",
        "disabled":"0"
    },
    "loader":{
        "prefix":"loader",
        "disabled":"0"
    },
    "info-box":{
        "prefix":"info-box",
        "disabled":"0"
    },
    "container":{
        "prefix":"container",
        "disabled":"0"
    },
    "backdrop":{
        "prefix":"backdrop",
        "disabled":"0"
    },
    "card-box":{
        "prefix":"card-box",
        "disabled":"0"
    },
    "center-box":{
        "prefix":"center-box",
        "disabled":"0"
    },
    "bottom-sheet":{
        "prefix":"bottom-sheet",
        "disabled":"0"
    },
    "toggle":{
        "prefix":"tgl",
        "disabled":"0"
    },
    "checkbox":{
        "prefix":"chkbx",
        "disabled":"0"
    }
}