const colors = {
    "0":{
        "heading":"Base",
        "colors":{
            0:{
                "id":"c00000",
                "label":"--Base-White"
            },
            1:{
                "id":"c00001",
                "label":"--Base-Black"
            }
        }
    },
    "1":{
        "heading":"Gray",
        "colors":{
            "0":{
                "id":"c00100",
                "label":"--Gray-2.5"
            },
            "1":{
                "id":"c00101",
                "label":"--Gray-05"
            },
            "2":{
                "id":"c00102",
                "label":"--Gray-10"
            },
            "3":{
                "id":"c00103",
                "label":"--Gray-20"
            },
            "4":{
                "id":"c00104",
                "label":"--Gray-30"
            },
            "5":{
                "id":"c00105",
                "label":"--Gray-40"
            },
            "6":{
                "id":"c00106",
                "label":"--Gray-base"
            },
            "7":{
                "id":"c00107",
                "label":"--Gray-60"
            },
            "8":{
                "id":"c00108",
                "label":"--Gray-70"
            },
            "9":{
                "id":"c00109",
                "label":"--Gray-80"
            },
            "10":{
                "id":"c00110",
                "label":"--Gray-90"
            },
            "11":{
                "id":"c00111",
                "label":"--Gray-95"
            }
        }
    },
    "2":{
        "heading":"Brand",
        "colors":{
            "0":{
                "id":"c00200",
                "label":"--Brand-2.5"
            },
            "1":{
                "id":"c00201",
                "label":"--Brand-05"
            },
            "2":{
                "id":"c00202",
                "label":"--Brand-10"
            },
            "3":{
                "id":"c00203",
                "label":"--Brand-20"
            },
            "4":{
                "id":"c00204",
                "label":"--Brand-30"
            },
            "5":{
                "id":"c00205",
                "label":"--Brand-40"
            },
            "6":{
                "id":"c00206",
                "label":"--Brand-base"
            },
            "7":{
                "id":"c00207",
                "label":"--Brand-60"
            },
            "8":{
                "id":"c00208",
                "label":"--Brand-70"
            },
            "9":{
                "id":"c00209",
                "label":"--Brand-80"
            },
            "10":{
                "id":"c00210",
                "label":"--Brand-90"
            },
            "11":{
                "id":"c00211",
                "label":"--Brand-95"
            }
        }
    },
    "3":{
        "heading":"Error",
        "colors":{
            "0":{
                "id":"c00300",
                "label":"--Error-2.5"
            },
            "1":{
                "id":"c00301",
                "label":"--Error-05"
            },
            "2":{
                "id":"c00302",
                "label":"--Error-10"
            },
            "3":{
                "id":"c00303",
                "label":"--Error-20"
            },
            "4":{
                "id":"c00304",
                "label":"--Error-30"
            },
            "5":{
                "id":"c00305",
                "label":"--Error-40"
            },
            "6":{
                "id":"c00306",
                "label":"--Error-base"
            },
            "7":{
                "id":"c00307",
                "label":"--Error-60"
            },
            "8":{
                "id":"c00308",
                "label":"--Error-70"
            },
            "9":{
                "id":"c00309",
                "label":"--Error-80"
            },
            "10":{
                "id":"c00310",
                "label":"--Error-90"
            },
            "11":{
                "id":"c00311",
                "label":"--Error-95"
            }
        }
    },
    "4":{
        "heading":"Warning",
        "colors":{
            "0":{
                "id":"c00400",
                "label":"--Warning-2.5"
            },
            "1":{
                "id":"c00401",
                "label":"--Warning-05"
            },
            "2":{
                "id":"c00402",
                "label":"--Warning-10"
            },
            "3":{
                "id":"c00403",
                "label":"--Warning-20"
            },
            "4":{
                "id":"c00404",
                "label":"--Warning-30"
            },
            "5":{
                "id":"c00405",
                "label":"--Warning-40"
            },
            "6":{
                "id":"c00406",
                "label":"--Warning-base"
            },
            "7":{
                "id":"c00407",
                "label":"--Warning-60"
            },
            "8":{
                "id":"c00408",
                "label":"--Warning-70"
            },
            "9":{
                "id":"c00409",
                "label":"--Warning-80"
            },
            "10":{
                "id":"c00410",
                "label":"--Warning-90"
            },
            "11":{
                "id":"c00411",
                "label":"--Warning-95"
            }
        }
    },
    "5":{
        "heading":"Success",
        "colors":{
            "0":{
                "id":"c00500",
                "label":"--Success-2.5"
            },
            "1":{
                "id":"c00501",
                "label":"--Success-05"
            },
            "2":{
                "id":"c00502",
                "label":"--Success-10"
            },
            "3":{
                "id":"c00503",
                "label":"--Success-20"
            },
            "4":{
                "id":"c00504",
                "label":"--Success-30"
            },
            "5":{
                "id":"c00505",
                "label":"--Success-40"
            },
            "6":{
                "id":"c00506",
                "label":"--Success-base"
            },
            "7":{
                "id":"c00507",
                "label":"--Success-60"
            },
            "8":{
                "id":"c00508",
                "label":"--Success-70"
            },
            "9":{
                "id":"c00509",
                "label":"--Success-80"
            },
            "10":{
                "id":"c00510",
                "label":"--Success-90"
            },
            "11":{
                "id":"c00511",
                "label":"--Success-95"
            }
        }
    },
    "6":{
        "heading":"Gray-blue",
        "colors":{
            "0":{
                "id":"c10000",
                "label":"--Gray-blue-2.5"
            },
            "1":{
                "id":"c10001",
                "label":"--Gray-blue-05"
            },
            "2":{
                "id":"c10002",
                "label":"--Gray-blue-10"
            },
            "3":{
                "id":"c10003",
                "label":"--Gray-blue-20"
            },
            "4":{
                "id":"c10004",
                "label":"--Gray-blue-30"
            },
            "5":{
                "id":"c10005",
                "label":"--Gray-blue-40"
            },
            "6":{
                "id":"c10006",
                "label":"--Gray-blue-base"
            },
            "7":{
                "id":"c10007",
                "label":"--Gray-blue-60"
            },
            "8":{
                "id":"c10008",
                "label":"--Gray-blue-70"
            },
            "9":{
                "id":"c10009",
                "label":"--Gray-blue-80"
            },
            "10":{
                "id":"c10010",
                "label":"--Gray-blue-90"
            },
            "11":{
                "id":"c10011",
                "label":"--Gray-blue-95"
            }
        }
    },
    "7":{
        "heading":"Gray cool",
        "colors":{
            "0":{
                "id":"c10100",
                "label":"--Gray-cool-2.5"
            },
            "1":{
                "id":"c10101",
                "label":"--Gray-cool-05"
            },
            "2":{
                "id":"c10102",
                "label":"--Gray-cool-10"
            },
            "3":{
                "id":"c10103",
                "label":"--Gray-cool-20"
            },
            "4":{
                "id":"c10104",
                "label":"--Gray-cool-30"
            },
            "5":{
                "id":"c10105",
                "label":"--Gray-cool-40"
            },
            "6":{
                "id":"c10106",
                "label":"--Gray-cool-base"
            },
            "7":{
                "id":"c10107",
                "label":"--Gray-cool-60"
            },
            "8":{
                "id":"c10108",
                "label":"--Gray-cool-70"
            },
            "9":{
                "id":"c10109",
                "label":"--Gray-cool-80"
            },
            "10":{
                "id":"c10110",
                "label":"--Gray-cool-90"
            },
            "11":{
                "id":"c10111",
                "label":"--Gray-cool-95"
            }
        }
    },
    "8":{
        "heading":"Gray modern",
        "colors":{
            "0":{
                "id":"c10200",
                "label":"--Gray-modern-2.5"
            },
            "1":{
                "id":"c10201",
                "label":"--Gray-modern-05"
            },
            "2":{
                "id":"c10202",
                "label":"--Gray-modern-10"
            },
            "3":{
                "id":"c10203",
                "label":"--Gray-modern-20"
            },
            "4":{
                "id":"c10204",
                "label":"--Gray-modern-30"
            },
            "5":{
                "id":"c10205",
                "label":"--Gray-modern-40"
            },
            "6":{
                "id":"c10206",
                "label":"--Gray-modern-base"
            },
            "7":{
                "id":"c10207",
                "label":"--Gray-modern-60"
            },
            "8":{
                "id":"c10208",
                "label":"--Gray-modern-70"
            },
            "9":{
                "id":"c10209",
                "label":"--Gray-modern-80"
            },
            "10":{
                "id":"c10210",
                "label":"--Gray-modern-90"
            },
            "11":{
                "id":"c10211",
                "label":"--Gray-modern-95"
            }
        }
    },
    "9":{
        "heading":"Gray neutral",
        "colors":{
            "0":{
                "id":"c10300",
                "label":"--Gray-neutral-2.5"
            },
            "1":{
                "id":"c10301",
                "label":"--Gray-neutral-05"
            },
            "2":{
                "id":"c10302",
                "label":"--Gray-neutral-10"
            },
            "3":{
                "id":"c10303",
                "label":"--Gray-neutral-20"
            },
            "4":{
                "id":"c10304",
                "label":"--Gray-neutral-30"
            },
            "5":{
                "id":"c10305",
                "label":"--Gray-neutral-40"
            },
            "6":{
                "id":"c10306",
                "label":"--Gray-neutral-base"
            },
            "7":{
                "id":"c10307",
                "label":"--Gray-neutral-60"
            },
            "8":{
                "id":"c10308",
                "label":"--Gray-neutral-70"
            },
            "9":{
                "id":"c10309",
                "label":"--Gray-neutral-80"
            },
            "10":{
                "id":"c10310",
                "label":"--Gray-neutral-90"
            },
            "11":{
                "id":"c10311",
                "label":"--Gray-neutral-95"
            }
        }
    },
    "10":{
        "heading":"Gray iron",
        "colors":{
            "0":{
                "id":"c10400",
                "label":"--Gray-iron-2.5"
            },
            "1":{
                "id":"c10401",
                "label":"--Gray-iron-05"
            },
            "2":{
                "id":"c10402",
                "label":"--Gray-iron-10"
            },
            "3":{
                "id":"c10403",
                "label":"--Gray-iron-20"
            },
            "4":{
                "id":"c10404",
                "label":"--Gray-iron-30"
            },
            "5":{
                "id":"c10405",
                "label":"--Gray-iron-40"
            },
            "6":{
                "id":"c10406",
                "label":"--Gray-iron-base"
            },
            "7":{
                "id":"c10407",
                "label":"--Gray-iron-60"
            },
            "8":{
                "id":"c10408",
                "label":"--Gray-iron-70"
            },
            "9":{
                "id":"c10409",
                "label":"--Gray-iron-80"
            },
            "10":{
                "id":"c10410",
                "label":"--Gray-iron-90"
            },
            "11":{
                "id":"c10411",
                "label":"--Gray-iron-95"
            }
        }
    },
    "11":{
        "heading":"Gray true",
        "colors":{
            "0":{
                "id":"c10500",
                "label":"--Gray-true-2.5"
            },
            "1":{
                "id":"c10501",
                "label":"--Gray-true-05"
            },
            "2":{
                "id":"c10502",
                "label":"--Gray-true-10"
            },
            "3":{
                "id":"c10503",
                "label":"--Gray-true-20"
            },
            "4":{
                "id":"c10504",
                "label":"--Gray-true-30"
            },
            "5":{
                "id":"c10505",
                "label":"--Gray-true-40"
            },
            "6":{
                "id":"c10506",
                "label":"--Gray-true-base"
            },
            "7":{
                "id":"c10507",
                "label":"--Gray-true-60"
            },
            "8":{
                "id":"c10508",
                "label":"--Gray-true-70"
            },
            "9":{
                "id":"c10509",
                "label":"--Gray-true-80"
            },
            "10":{
                "id":"c10510",
                "label":"--Gray-true-90"
            },
            "11":{
                "id":"c10511",
                "label":"--Gray-true-95"
            }
        }
    },
    "12":{
        "heading":"Gray warm",
        "colors":{
            "0":{
                "id":"c10600",
                "label":"--Gray-warm-2.5"
            },
            "1":{
                "id":"c10601",
                "label":"--Gray-warm-05"
            },
            "2":{
                "id":"c10602",
                "label":"--Gray-warm-10"
            },
            "3":{
                "id":"c10603",
                "label":"--Gray-warm-20"
            },
            "4":{
                "id":"c10604",
                "label":"--Gray-warm-30"
            },
            "5":{
                "id":"c10605",
                "label":"--Gray-warm-40"
            },
            "6":{
                "id":"c10606",
                "label":"--Gray-warm-base"
            },
            "7":{
                "id":"c10607",
                "label":"--Gray-warm-60"
            },
            "8":{
                "id":"c10608",
                "label":"--Gray-warm-70"
            },
            "9":{
                "id":"c10609",
                "label":"--Gray-warm-80"
            },
            "10":{
                "id":"c10610",
                "label":"--Gray-warm-90"
            },
            "11":{
                "id":"c10611",
                "label":"--Gray-warm-95"
            }
        }
    },
    "13":{
        "heading":"Moss",
        "colors":{
            "0":{
                "id":"c10700",
                "label":"--Moss-2.5"
            },
            "1":{
                "id":"c10701",
                "label":"--Moss-05"
            },
            "2":{
                "id":"c10702",
                "label":"--Moss-10"
            },
            "3":{
                "id":"c10703",
                "label":"--Moss-20"
            },
            "4":{
                "id":"c10704",
                "label":"--Moss-30"
            },
            "5":{
                "id":"c10705",
                "label":"--Moss-40"
            },
            "6":{
                "id":"c10706",
                "label":"--Moss-base"
            },
            "7":{
                "id":"c10707",
                "label":"--Moss-60"
            },
            "8":{
                "id":"c10708",
                "label":"--Moss-70"
            },
            "9":{
                "id":"c10709",
                "label":"--Moss-80"
            },
            "10":{
                "id":"c10710",
                "label":"--Moss-90"
            },
            "11":{
                "id":"c10711",
                "label":"--Moss-95"
            }
        }
    },
    "14":{
        "heading":"Green light",
        "colors":{
            "0":{
                "id":"c10800",
                "label":"--Green-light-2.5"
            },
            "1":{
                "id":"c10801",
                "label":"--Green-light-05"
            },
            "2":{
                "id":"c10802",
                "label":"--Green-light-10"
            },
            "3":{
                "id":"c10803",
                "label":"--Green-light-20"
            },
            "4":{
                "id":"c10804",
                "label":"--Green-light-30"
            },
            "5":{
                "id":"c10805",
                "label":"--Green-light-40"
            },
            "6":{
                "id":"c10806",
                "label":"--Green-light-base"
            },
            "7":{
                "id":"c10807",
                "label":"--Green-light-60"
            },
            "8":{
                "id":"c10808",
                "label":"--Green-light-70"
            },
            "9":{
                "id":"c10809",
                "label":"--Green-light-80"
            },
            "10":{
                "id":"c10810",
                "label":"--Green-light-90"
            },
            "11":{
                "id":"c10811",
                "label":"--Green-light-95"
            }
        }
    },
    "15":{
        "heading":"Green",
        "colors":{
            "0":{
                "id":"c10900",
                "label":"--Green-2.5"
            },
            "1":{
                "id":"c10901",
                "label":"--Green-05"
            },
            "2":{
                "id":"c10902",
                "label":"--Green-10"
            },
            "3":{
                "id":"c10903",
                "label":"--Green-20"
            },
            "4":{
                "id":"c10904",
                "label":"--Green-30"
            },
            "5":{
                "id":"c10905",
                "label":"--Green-40"
            },
            "6":{
                "id":"c10906",
                "label":"--Green-base"
            },
            "7":{
                "id":"c10907",
                "label":"--Green-60"
            },
            "8":{
                "id":"c10908",
                "label":"--Green-70"
            },
            "9":{
                "id":"c10909",
                "label":"--Green-80"
            },
            "10":{
                "id":"c10910",
                "label":"--Green-90"
            },
            "11":{
                "id":"c10911",
                "label":"--Green-95"
            }
        }
    }
}

module.exports = colors;