import ButtonGroup from 'aio-global-raw-ui/atoms/form/button-group';

export default {
	title:"Atoms/Form/ButtonGroup",
	argTypes:{

	},
	component:ButtonGroup,
	tags:['autodocs'],
	parameters:{
		layout:"centered",
		docs:{
			description:{
				component:"Button Group is a reusable React UI component designed to display and manage a collection of related buttons as a single, cohesive control. It provides a consistent way to group actions or selections across the application while supporting customizable button configurations, themes, states, and layouts. Each button within the group can be individually configured with its own label, icons, behavior, and styling, enabling flexible and interactive user experiences.<br/><br/><strong>Import path:</strong><code>import ButtonGroup from 'aio-global-raw-ui/atoms/form/button-group';</code><br/><br/><strong>Component directory:</strong><code>./libs/frontend/ui/raw/atoms/form/button-group/index</code><br/><br/>"
			}
		}
	},
	mockdata:{
		defaults:{
			list:{
				0:{
					button:{
						content:"1"
					},
					icons:{
						left:{
							config:{
								icon:{
									name:"bell"
								}
							}
						}
					}
				},
				1:{
					button:{
						content:"2"
					}
				},
				2:{
					button:{
						content:"3"
					}
				}
			}
		},
		variants:{

		}
	}
}

export const Base = {
	args:{
		list:{
			0:{
				button:{
					content:"1"
				},
				icons:{
					left:{
						config:{
							icon:{
								name:"bell"
							}
						}
					}
				}
			},
			1:{
				button:{
					content:"2"
				}
			},
			2:{
				button:{
					content:"3"
				}
			}
		},
		callback:{
			onBlur:null,
			onFocus:null,
			onPress:null,
			onClick:null,
			onPressUp:null,
			onPressEnd:null,
			onPressStart:null,
			onPressChange:null
		},
		theme:{
			active:{
				callback:{
					onBlur:null,
					onFocus:null,
					onPress:null,
					onClick:null,
					onPressUp:null,
					onPressEnd:null,
					onPressStart:null,
					onPressChange:null
				},
				button:{
					markup:{
						element:"button"
					},
					ariaProps:{

					},
					states:{
						hover:false,
						active:false,
						disabled:false,
						wait:{
							enabled:false,
							content:''
						}
					}
				},
				icons:{
					left:{
						config:{
							markup:{
								element:"span"
							},
							type:"font",
							svg:{
								style:{

								},
								size:"24px"
							},
							icon:{
								name:'',
								size:"24",
								family:"g"
							}
						}
					},
					right:{
						config:{
							markup:{
								element:"span"
							},
							type:"font",
							svg:{
								style:{

								},
								size:"24px"
							},
							icon:{
								name:'',
								size:"24",
								family:"g"
							}
						}
					}
				}
			},
			disabled:{
				callback:{
					onBlur:null,
					onFocus:null,
					onPress:null,
					onClick:null,
					onPressUp:null,
					onPressEnd:null,
					onPressStart:null,
					onPressChange:null
				},
				button:{
					markup:{
						element:"button"
					},
					ariaProps:{

					},
					states:{
						hover:false,
						active:false,
						disabled:false,
						wait:{
							enabled:false,
							content:''
						}
					}
				},
				icons:{
					left:{
						config:{
							markup:{
								element:"span"
							},
							type:"font",
							svg:{
								style:{

								},
								size:"24px"
							},
							icon:{
								name:'',
								size:"24",
								family:"g"
							}
						}
					},
					right:{
						config:{
							markup:{
								element:"span"
							},
							type:"font",
							svg:{
								style:{

								},
								size:"24px"
							},
							icon:{
								name:'',
								size:"24",
								family:"g"
							}
						}
					}
				}
			},
			default:{
				callback:{
					onBlur:null,
					onFocus:null,
					onPress:null,
					onClick:null,
					onPressUp:null,
					onPressEnd:null,
					onPressStart:null,
					onPressChange:null
				},
				button:{
					markup:{
						element:"button"
					},
					ds:{
						predefined:{
							size:"sm"
						},
						css:{
							class:{
								shadow:"sm"
							}
						}
					},
					ariaProps:{

					},
					states:{
						hover:false,
						active:false,
						disabled:false,
						wait:{
							enabled:false,
							content:''
						}
					}
				},
				icons:{
					left:{
						config:{
							markup:{
								element:"span"
							},
							type:"font",
							svg:{
								style:{

								},
								size:"24px"
							},
							icon:{
								name:'',
								size:"24",
								family:"g"
							}
						}
					},
					right:{
						config:{
							markup:{
								element:"span"
							},
							type:"font",
							svg:{
								style:{

								},
								size:"24px"
							},
							icon:{
								name:'',
								size:"24",
								family:"g"
							}
						}
					}
				}
			}
		}
	}
}