import Badge from 'aio-global-raw-ui/atoms/badge';

export default {
	title:"Atoms/Badge",
	argTypes:{

	},
	component:Badge,
	tags:['autodocs'],
	parameters:{
		layout:"centered",
		docs:{
			description:{
				component:"Bubble is a UI component used to display a small, visually distinct piece of information within a rounded or speech-bubble-like container. It is commonly used for messages, notifications, labels, status indicators, tags, or contextual content, helping important information stand out from surrounding content.<br/><br/><strong>Import path:</strong><code>import Badge from 'aio-global-raw-ui/atoms/badge';</code><br/><br/><strong>Component directory:</strong><code>./libs/frontend/ui/raw/atoms/badge/index</code><br/><br/>"
			}
		}
	},
	mockdata:{
		defaults:{
			content:"Bubble"
		},
		variants:{

		}
	}
}

export const Base = {
	args:{
		content:"Bubble",
		avatars:{
			right:{
				nowrapper:false,
				config:{
					initial:{
						ds:{
							css:{
								class:{
									family:"md",
									fontsize:"sm"
								}
							}
						}
					}
				},
				image:{
					src:''
				},
				initial:{
					display:false
				},
				icon:{
					config:{
						markup:{
							element:"span"
						},
						type:"font",
						svg:{
							style:{

							},
							size:"24px"
						},
						icon:{
							name:"home",
							size:"24",
							family:"g"
						}
					}
				},
				enable:false
			},
			left:{
				nowrapper:false,
				config:{
					initial:{
						ds:{
							css:{
								class:{
									family:"md",
									fontsize:"sm"
								}
							}
						}
					}
				},
				image:{
					src:''
				},
				initial:{
					display:false
				},
				icon:{
					config:{
						markup:{
							element:"span"
						},
						type:"font",
						svg:{
							style:{

							},
							size:"24px"
						},
						icon:{
							name:"home",
							size:"24",
							family:"g"
						}
					}
				},
				enable:false
			}
		},
		icons:{
			left:{
				config:{
					markup:{
						element:"span"
					},
					type:"font",
					svg:{
						style:{

						},
						size:"24px"
					},
					icon:{
						name:"home",
						size:"24",
						family:"g"
					}
				}
			},
			right:{
				config:{
					markup:{
						element:"span"
					},
					type:"font",
					svg:{
						style:{

						},
						size:"24px"
					},
					icon:{
						name:"bell",
						size:"24",
						family:"g"
					}
				}
			}
		},
		config:{
			content:{
				markup:{
					element:"p"
				}
			},
			wrapper:{
				markup:{
					element:"div"
				},
				ds:{
					predefined:{
						background:"c00504"
					}
				}
			}
		}
	}
}