const config = {

    ENUMS:{
        LAST__ITEM__ENUM:'__LAST__ITEM__ENUM__'
    },

    markup:{
        tags:{
            0:{
                "id":"html",
                "label":"html"
            },
            1:{
                "id":"head",
                "label":"head"
            },
            2:{
                "id":"body",
                "label":"body"
            },
            3:{
                "id":"section",
                "label":"section"
            },
            4:{
                "id":"header",
                "label":"header"
            },
            5:{
                "id":"footer",
                "label":"footer"
            }
        }
    },

    languages:{
        0:{
            "id":"en",
            "label":"English"
        },
        2:{
            "id":"hi",
            "label":"Hindi"
        },
        3:{
            "id":"pb",
            "label":"Punjabi"
        }
    },

    model:{
        childs:{
            0:{
                "id":"query",
                "label":"Query"
            },
            2:{
                "id":"pagination",
                "label":"Pagination"
            },
            3:{
                "id":"signature",
                "label":"Signature"
            },
            4:{
                "id":"md5Hash",
                "label":"Md5 hash"
            },
            5:{
                "id":"valuemap",
                "label":"Valuemap"
            },
            6:{
                "id":"response",
                "label":"Response"
            }
        },
        query:{
            operations:{
                like:{
                    0:{
                        "id":"list",
                        "label":"List",
                        "value":{
                            regexType:"list"
                        }
                    },
                    1:{
                        "id":"match",
                        "label":"Match",
                        "value":{
                            regexType:"match"
                        }
                    },
                    2:{
                        "id":"startsWith",
                        "label":"Starts with",
                        "value":{
                            regexType:"startsWith"
                        }
                    }
                },
                list:{
                    0:{
                        "id":"eq",
                        "label":"Equal",
                        "value":{
                            opType:"eq"
                        }
                    },
                    1:{
                        "id":"lt",
                        "label":"Less than",
                        "value":{
                            opType:"lt"
                        }
                    },
                    2:{
                        "id":"lte",
                        "label":"Less than equal",
                        "value":{
                            opType:"lte"
                        }
                    },
                    3:{
                        "id":"gt",
                        "label":"Greater than",
                        "value":{
                            opType:"gt"
                        }
                    },
                    4:{
                        "id":"gte",
                        "label":"Greater than equal",
                        "value":{
                            opType:"gte"
                        }
                    },
                    5:{
                        "id":"regex",
                        "label":"Like",
                        "value":{
                            opType:"regex"
                        }
                    }
                }
            },
            modes:{
                0:{
                    "id":"logical",
                    "label":"Conditional"
                },
                1:{
                    "id":"query",
                    "label":"Query"
                }
            },
            conditions:{
                0:{
                    "id":"and",
                    "label":"And"
                },
                1:{
                    "id":"or",
                    "label":"Or"
                }
            },
            hiddenCloumns:{
                0:{
                    id:"userId",
                    label:"User Id"
                },
                1:{
                    id:"merchantId",
                    label:"Merchant Id"
                },
                2:{
                    id:"deleted",
                    label:"Deleted"
                }
            },
            deleteIncludeOptions:{
                0:{
                    id:"all",
                    label:"All"
                },
                1:{
                    id:"active",
                    label:"Active only"
                },
                2:{
                    id:"deleted",
                    label:"Deleted Only"
                }
            }
        }
    },

    method:{
        childs:{
            0:{
                "id":"method.details",
                "label":"Method details"
            },
            2:{
                "id":"method.data.config",
                "label":"Data config"
            }
        },
    },

    collection:{
        childs:{
            0:{
                "id":"collection.id",
                "label":"Collection map"
            }
        },
    },

    validation:{
        childs:{
            0:{
                "id":"request.server.config",
                "label":"Server config"
            },
            2:{
                "id":"request.data.config",
                "label":"Data config"
            }
        },
        serverConfigs:{
            childs:{
                0:{
                    "id":"request.method",
                    "label":"Request method"
                },
                2:{
                    "id":"request.body.data",
                    "label":"Request body data"
                }
            }
        },
        checks:{
            requiredAndOptional:{
                0:{
                    'id':'required',
                    'label':'Required'
                },
                1:{
                    'id':'optional',
                    'label':'Optional'
                },
            },
            required:{
                0:{
                    'id':'required',
                    'label':'Required'
                },
                1:{
                    'id':'optional',
                    'label':'Optional'
                },
                2:{
                    'id':'mobile',
                    'label':'Mobile'
                }
            },
            types:{
                0:{
                    "id":"default",
                    "label":"Default"
                },
                1:{
                    "id":"required",
                    "label":"Required"
                },
                2:{
                    "id":"lengths",
                    "label":"Lengths"
                },
                3:{
                    "id":"maxvalue",
                    "label":"Max value"
                },
                4:{
                    "id":"minvalue",
                    "label":"Min value"
                },
                5:{
                    "id":"minlength",
                    "label":"Min length"
                },
                6:{
                    "id":"maxlength",
                    "label":"Max length"
                },
                7:{
                    "id":"regex",
                    "label":"Regex"
                },
                8:{
                    "id":"enums",
                    "label":"Enums"
                },
                9:{
                    "id":"object",
                    "label":"Object"
                }
            }
        },
        data:{
            options:{
                0:{
                    "id":"body",
                    "label":"Body"
                },
                1:{
                    "id":"query",
                    "label":"Query"
                },
                2:{
                    "id":"params",
                    "label":"Params"
                },
                3:{
                    "id":"headers",
                    "label":"Headers"
                },
                4:{
                    "id":"cookies",
                    "label":"Cookies"
                }
            },
            fromOptions:{
                0:{
                    'id':'body',
                    'label':'Body data'
                },
                1:{
                    'id':'body-item',
                    'label':'Body item data'
                },
                2:{
                    'id':'query',
                    'label':'Query string'
                },
                3:{
                    'id':'params',
                    'label':'Url Params'
                },
                4:{
                    'id':'appConfig',
                    'label':'App Config'
                },
                5:{
                    'id':'merchant',
                    'label':'Merchant details'
                },
                6:{
                    'id':'env',
                    'label':'Environments variables'
                },
                7:{
                    "id":'auth',
                    "label":"Auth details"
                },
                8:{
                    "id":'session',
                    "label":"Session details"
                }
            }
        },
        actions:{
            0:{
                "id":"fetch",
                "label":"View"
            },
            1:{
                "id":"update",
                "label":"Update"
            },
            2:{
                "id":"create",
                "label":"Create"
            },
            3:{
                "id":"remove",
                "label":"Delete"
            }
        },
        methods:{
            0:{
                "id":"get",
                "label":"Get"
            },
            1:{
                "id":"put",
                "label":"Put"
            },
            2:{
                "id":"post",
                "label":"Post"
            },
            3:{
                "id":"delete",
                "label":"Delete"
            }
        },
        params:{
            list:{
                0:{
                    "id":"primary",
                    "label":"Primary"
                },
                1:{
                    "id":"secondary",
                    "label":"Secondary"
                },
                2:{
                    "id":"tertiary",
                    "label":"Tertiary"
                },
                3:{
                    "id":"quartary",
                    "label":"Quartary"
                },
                4:{
                    "id":"quinary",
                    "label":"quinary"
                },
                5:{
                    "id":"senary",
                    "label":"Senary"
                },
                6:{
                    "id":"septenary",
                    "label":"Septenary"
                },
                7:{
                    "id":"octonary",
                    "label":"Octonary"
                },
                8:{
                    "id":"nonary",
                    "label":"Nonary"
                },
                9:{
                    "id":"decenary",
                    "label":"Decenary"
                },
            }
        },
        body:{
            type:{
                0:{
                    "id":"list",
                    "label":"List"
                },
                1:{
                    "id":"object",
                    "label":"Object"
                }
            },
            requireOptions:{
                0:{
                    "id":"optional",
                    "label":"Optional"
                },
                1:{
                    "id":"required",
                    "label":"Required"
                },
                2:{
                    "id":"nothing",
                    "label":"Blank"
                }
            }
        }
    },
    controller:{
        routes:{
            0:{
                "id":"controller",
                "label":"Controller"
            },
            1:{
                "id":"action",
                "label":"Action"
            },
            2:{
                "id":"version",
                "label":"Version"
            },
            3:{
                "id":"job",
                "label":"Job"
            },
            4:{
                "id":"method",
                "label":"Method"
            }
        }
    }
}

export default config;