import Item from 'aio-global-raw-ui/atoms/tree-list/item';

export default {
	title:"Raw/Atoms/TreeList/Item",
	argTypes:{

	},
	component:Item,
	tags:['autodocs'],
	parameters:{
		layout:"centered",
		docs:{
			description:{
				component:"The Button component is a reusable React UI component designed to provide a consistent button experience across the application. It supports customizable content, styling, and optional icons on both the left and right sides of the button label.<br/><br/><strong class="fm-md">Import path:</strong><code class="pd-2 bg-c00101 bdr-4 mr-l6 bdr-1 bdr-c00104">import Item from 'aio-global-raw-ui/atoms/tree-list/item';</code><br/><br/><strong class="fm-md">Component directory:</strong><code class="pd-2 bg-c00101 bdr-4 mr-l6 bdr-1 bdr-c00104">./libs/frontend/ui/raw/atoms/tree-list/item/index</code><br/><br/>"
			}
		}
	},
	mockdata:{
		defaults:{

		},
		variants:{

		}
	}
}

export const Base = {
	args:{
		callbacks:{
			end:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			after:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			start:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			before:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			center:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			wrapper:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			}
		},
		childs:{
			start:'',
			before:'',
			center:'',
			end:'',
			after:''
		},
		config:{
			center:{
				markup:{
					element:"div"
				}
			},
			wrapper:{
				markup:{
					element:"li"
				},
				ds:{
					css:{
						class:{
							cursor:"cp",
							fontsize:"sm",
							padding:{
								1:8,
								2:12
							}
						}
					}
				}
			},
			end:{
				markup:{
					element:"div"
				}
			},
			after:{
				markup:{
					element:"div"
				}
			},
			start:{
				markup:{
					element:"div"
				},
				ds:{
					css:{
						class:{
							margin:{
								1:0,
								2:8,
								3:0,
								4:0
							}
						}
					}
				}
			},
			before:{
				markup:{
					element:"div"
				}
			}
		},
		expendIcon:{
			exclude:false,
			show:true,
			placement:"start",
			names:{
				selected:"arrow-down",
				default:"arrow-right"
			},
			config:{
				config:{
					markup:{
						element:"span"
					},
					type:"font",
					svg:{
						style:{

						},
						size:"20px"
					},
					icon:{
						name:"home",
						size:"20",
						family:"g"
					},
					dataAttrIconConfig:false
				}
			}
		},
		kies:{
			label:"label"
		},
		data:{

		},
		disabled:false,
		state:"default",
		theme:{
			default:{
				wrapper:{
					predefined:{
						background:"c00000",
						hbackground:"c00101"
					}
				}
			},
			selected:{
				wrapper:{
					predefined:{
						background:"c00101"
					}
				}
			},
			disabled:{
				wrapper:{
					predefined:{
						color:"c00105",
						background:"c00101"
					}
				}
			}
		}
	}
}