const helpers = process.uiHelpers();
const props = require('./../props');

const avatar = (arg) => {
    return helpers.json.merge({
        ___:{
            asroot:false,
            compProps:{
                overwirte:{
                    icon:null,
                    enable:null,
                    initial:null,
                    dsTheme:{
                        ___:{
                            predefined:{
                                overwirte:{
                                    outer:{
                                        dvalue:0,
                                    },
                                    size:{
                                        dvalue:16
                                    }
                                }
                            }
                        }
                    },
                    config:{
                        ___:{
                            nested:{
                                initial:null,
                                wrapper:{
                                    ___:{
                                        predefined:{
                                            overwirte:{
                                                markup:{
                                                    ___:{
                                                        nested:{
                                                            element:{
                                                                dvalue:'span'
                                                            }
                                                        }
                                                    }
                                                },
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }, arg || {});
}

module.exports = helpers.json.merge(props || {}, {
    icons:null,
    avatars:{
        ___:{
            nested:{
                right:avatar({
                    ___:{
                        compProps:{
                            overwirte:{
                                config:{
                                    ___:{
                                        nested:{
                                            wrapper:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            ds:{
                                                                ___:{
                                                                    nested:{
                                                                        css:{
                                                                            ___:{
                                                                                nested:{
                                                                                    class:{
                                                                                        ___:{
                                                                                            nested:{
                                                                                                margin:{
                                                                                                    ___:{
                                                                                                        nested:{
                                                                                                            1:{
                                                                                                                dvalue:0
                                                                                                            },
                                                                                                            2:{
                                                                                                                dvalue:0
                                                                                                            },
                                                                                                            3:{
                                                                                                                dvalue:0
                                                                                                            },
                                                                                                            4:{
                                                                                                                dvalue:6
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                            }
                        }
                    }
                }),
                left:avatar({
                    ___:{
                        compProps:{
                            overwirte:{
                                config:{
                                    ___:{
                                        nested:{
                                            wrapper:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            ds:{
                                                                ___:{
                                                                    nested:{
                                                                        css:{
                                                                            ___:{
                                                                                nested:{
                                                                                    class:{
                                                                                        ___:{
                                                                                            nested:{
                                                                                                margin:{
                                                                                                    ___:{
                                                                                                        nested:{
                                                                                                            1:{
                                                                                                                dvalue:0
                                                                                                            },
                                                                                                            2:{
                                                                                                                dvalue:6
                                                                                                            },
                                                                                                            3:{
                                                                                                                dvalue:0
                                                                                                            },
                                                                                                            4:{
                                                                                                                dvalue:0
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                            }
                        }
                    }
                })
            }
        }
    }
});