import TreeRow from 'aio-global-raw-ui/atoms/tree-row';

export default {
	title:"Raw/Atoms/TreeRow",
	argTypes:{

	},
	component:TreeRow,
	tags:['autodocs'],
	parameters:{
		layout:"centered",
		docs:{
			description:{
				component:"Tree layout is a reusable layout component that divides content into five distinct sections: start, before, center, after, and end. Parent components can pass dynamic child elements as props, which are rendered in their respective sections. This flexible structure enables developers to customize the layout while maintaining consistency across the application, making the component highly reusable for a variety of UI scenarios.<br/><br/><strong class="fm-md">Import path:</strong><code class="pd-2 bg-c00101 bdr-4 mr-l6 bdr-1 bdr-c00104">import TreeRow from 'aio-global-raw-ui/atoms/tree-row';</code><br/><br/><strong class="fm-md">Component directory:</strong><code class="pd-2 bg-c00101 bdr-4 mr-l6 bdr-1 bdr-c00104">./libs/frontend/ui/raw/atoms/tree-row/index</code><br/><br/>"
			}
		}
	},
	mockdata:{
		defaults:{
			childs:{
				center:"Tree label"
			},
			config:{

			}
		},
		variants:{

		}
	}
}

export const Base = {
	args:{
		callbacks:{
			end:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			after:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			start:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			before:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			center:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			},
			wrapper:{
				onClick:null,
				dsTheme:null,
				beforeRender:null
			}
		},
		childs:{
			start:'',
			before:'',
			center:"Tree label",
			end:'',
			after:''
		},
		config:{
			center:{
				markup:{
					element:"div"
				}
			},
			wrapper:{
				markup:{
					element:"div"
				},
				ds:{
					css:{
						class:{
							cursor:"cp",
							fontsize:"sm",
							padding:{
								1:8,
								2:12
							}
						}
					}
				}
			},
			end:{
				markup:{
					element:"div"
				}
			},
			after:{
				markup:{
					element:"div"
				}
			},
			start:{
				markup:{
					element:"div"
				},
				ds:{
					css:{
						class:{
							margin:{
								1:0,
								2:8,
								3:0,
								4:0
							}
						}
					}
				}
			},
			before:{
				markup:{
					element:"div"
				}
			}
		},
		expendIcon:{
			exclude:false,
			show:true,
			state:"default",
			placement:"start",
			names:{
				selected:"arrow-down",
				default:"arrow-right"
			},
			config:{
				config:{
					markup:{
						element:"span"
					},
					type:"font",
					svg:{
						style:{

						},
						size:"20px"
					},
					icon:{
						name:"home",
						size:"20",
						family:"g"
					},
					dataAttrIconConfig:false
				}
			}
		}
	}
}