import Select from 'aio-global-raw-ui/atoms/form/select';

export default {
	title:"Atoms/Form/Select",
	argTypes:{

	},
	component:Select,
	tags:['autodocs'],
	parameters:{
		layout:"centered",
		docs:{
			description:{
				component:"The Button component is a reusable React UI component designed to provide a consistent button experience across the application. It supports customizable content, styling, and optional icons on both the left and right sides of the button label.<br/><br/><strong>Import path:</strong><code>import Select from 'aio-global-raw-ui/atoms/form/select';</code><br/><br/><strong>Component directory:</strong><code>./libs/frontend/ui/raw/atoms/form/select/index</code><br/><br/>"
			}
		}
	},
	mockdata:{
		defaults:{

		},
		variants:{

		}
	}
}

export const Base = {
	args:{
		open:false,
		multiple:false,
		searchable:true,
		allowDeselect:true,
		closeOnSelect:true,
		keymap:{
			label:"label",
			selection:"value"
		},
		content:{
			noResult:{
				default:"No selectable items found",
				orginial:"No selectable items found",
				filtered:"filtered"
			}
		},
		dropdown:{
			controls:{
				open:false,
				arrow:false,
				mode:"react",
				toggle:"click",
				position:"bottom-right"
			},
			config:{
				wrapper:{
					markup:{
						element:"div"
					}
				},
				container:{
					markup:{
						element:"div"
					}
				},
				content:{
					markup:{
						element:"div"
					}
				},
				layer:{
					markup:{
						element:"div"
					}
				}
			}
		},
		input:{
			value:'',
			defaultValue:'',
			label:'',
			id:'',
			name:'',
			type:"text",
			error:'',
			description:'',
			placeholder:'',
			maxlength:100,
			minLength:2,
			debounceDelay:500,
			eye:true,
			invalid:false,
			disabled:false,
			required:false,
			readonly:false,
			clearable:false,
			prefix:false,
			suffix:false,
			callback:{
				onCut:null,
				onCopy:null,
				onBlur:null,
				onEnter:null,
				onFocus:null,
				onInput:null,
				onPaste:null,
				onSelect:null,
				onKeyUp:null,
				onKeyDown:null,
				onChange:null,
				onChangeEnd:null,
				onChangeStart:null,
				onBeforeInput:null,
				onCompositionEnd:null,
				onCompositionStart:null,
				onCompositionUpdate:null
			},
			icons:{
				left:{
					config:{
						markup:{
							element:"span"
						},
						type:"font",
						svg:{
							style:{

							},
							size:"24px"
						},
						icon:{
							name:'',
							size:"24",
							family:"g"
						}
					}
				},
				right:{
					config:{
						markup:{
							element:"span"
						},
						type:"font",
						svg:{
							style:{

							},
							size:"24px"
						},
						icon:{
							name:'',
							size:"24",
							family:"g"
						}
					}
				},
				clear:{
					config:{
						markup:{
							element:"span"
						},
						type:"font",
						svg:{
							style:{

							},
							size:"24px"
						},
						icon:{
							name:'',
							size:"24",
							family:"g"
						}
					}
				}
			},
			config:{
				wrapper:{
					ds:{
						predefined:{
							default:{
								size:"xl",
								theme:"000"
							}
						}
					}
				}
			}
		},
		selectedIcon:{
			config:{
				markup:{
					element:"span"
				},
				type:"font",
				svg:{
					style:{

					},
					size:"24px"
				},
				icon:{
					name:"check",
					size:"24",
					family:"g"
				}
			},
			enabled:true,
			placement:"end"
		},
		listbox:{
			default:{
				data:{

				},
				defaults:{
					values:"rkjjeMGUNLx726080442691085920",
					childs:{
						item:{
							end:"rkjjeMGUNLx726080442691085920",
							after:"rkjjeMGUNLx726080442691085920",
							start:"rkjjeMGUNLx726080442691085920",
							before:"rkjjeMGUNLx726080442691085920",
							center:"rkjjeMGUNLx726080442691085920"
						},
						header:{
							end:"rkjjeMGUNLx726080442691085920",
							after:"rkjjeMGUNLx726080442691085920",
							start:"rkjjeMGUNLx726080442691085920",
							before:"rkjjeMGUNLx726080442691085920",
							center:"rkjjeMGUNLx726080442691085920"
						}
					}
				},
				mapping:{
					item:{
						end:'',
						after:'',
						start:'',
						before:'',
						center:"label"
					},
					header:{
						end:'',
						after:'',
						start:'',
						before:'',
						center:"label"
					},
					keys:{
						type:"type"
					}
				},
				callbacks:{
					item:{
						onClick:null,
						onBlur:null,
						onFocus:null,
						onKeyUp:null,
						dsTheme:null,
						onKeyDown:null,
						onDragStart:null,
						onMouseDown:null,
						onPointerUp:null,
						onPointerDown:null,
						onPointerEnter:null,
						onPointerLeave:null,
						beforeRender:null
					},
					header:{
						onClick:null,
						onBlur:null,
						onFocus:null,
						onKeyUp:null,
						dsTheme:null,
						onKeyDown:null,
						onDragStart:null,
						onMouseDown:null,
						onPointerUp:null,
						onPointerDown:null,
						onPointerEnter:null,
						onPointerLeave:null,
						beforeRender:null
					}
				},
				config:{
					item:{
						childs:{
							start:'',
							before:'',
							center:'',
							end:'',
							after:''
						},
						config:{
							center:{
								markup:{
									element:"div"
								}
							},
							wrapper:{
								markup:{
									element:"li"
								},
								ds:{
									predefined:{
										border:"c10104",
										font__d__size:"sm",
										className:"item-list bdr-1 bxs full"
									},
									css:{
										class:{
											borderNone:{
												1:true,
												2:true,
												3:false,
												4:true
											},
											padding:{
												1:12,
												2:12
											}
										}
									}
								}
							},
							end:{
								markup:{
									element:"div"
								},
								ds:{
									css:{
										class:{
											padding:{
												1:0,
												2:0,
												3:0,
												4:8
											}
										}
									}
								}
							},
							after:{
								markup:{
									element:"div"
								},
								ds:{
									css:{
										class:{
											padding:{
												1:0,
												2:0,
												3:0,
												4:8
											}
										}
									}
								}
							},
							start:{
								markup:{
									element:"div"
								},
								ds:{
									css:{
										class:{
											padding:{
												1:0,
												2:8,
												3:0,
												4:0
											}
										}
									}
								}
							},
							before:{
								markup:{
									element:"div"
								},
								ds:{
									css:{
										class:{
											padding:{
												1:0,
												2:8,
												3:0,
												4:0
											}
										}
									}
								}
							}
						}
					},
					header:{
						childs:{
							start:'',
							before:'',
							center:'',
							end:'',
							after:''
						},
						config:{
							center:{
								markup:{
									element:"div"
								}
							},
							wrapper:{
								markup:{
									element:"li"
								},
								ds:{
									predefined:{
										border:"c10104",
										font__d__size:"sb",
										className:"item-header bdr-1 bxs full"
									},
									css:{
										class:{
											borderNone:{
												1:true,
												2:true,
												3:false,
												4:true
											},
											padding:{
												1:12,
												2:12
											}
										}
									}
								}
							},
							end:{
								markup:{
									element:"div"
								},
								ds:{
									css:{
										class:{
											padding:{
												1:0,
												2:0,
												3:0,
												4:8
											}
										}
									}
								}
							},
							after:{
								markup:{
									element:"div"
								},
								ds:{
									css:{
										class:{
											padding:{
												1:0,
												2:0,
												3:0,
												4:8
											}
										}
									}
								}
							},
							start:{
								markup:{
									element:"div"
								},
								ds:{
									css:{
										class:{
											padding:{
												1:0,
												2:8,
												3:0,
												4:0
											}
										}
									}
								}
							},
							before:{
								markup:{
									element:"div"
								},
								ds:{
									css:{
										class:{
											padding:{
												1:0,
												2:8,
												3:0,
												4:0
											}
										}
									}
								}
							}
						}
					},
					wrapper:{
						markup:{
							element:"ul"
						},
						ds:{
							predefined:{
								radius:"6",
								border:"c10104"
							}
						}
					},
					noresults:{
						markup:{
							element:"li"
						}
					}
				}
			},
			disabled:{
				config:{
					item:{
						config:{
							wrapper:{
								ds:{
									predefined:{
										border:"c10104",
										font__d__size:"sm",
										className:"item-list bdr-1 bxs full"
									}
								}
							}
						}
					},
					header:{
						config:{
							wrapper:{
								ds:{
									predefined:{
										border:"c10104",
										font__d__size:"sb",
										className:"item-header bdr-1 bxs full"
									}
								}
							}
						}
					},
					wrapper:{
						markup:{
							element:"ul"
						},
						ds:{
							predefined:{
								radius:"6",
								border:"c10104"
							}
						}
					},
					noresults:{
						markup:{
							element:"li"
						}
					}
				}
			},
			selected:{
				config:{
					item:{
						config:{
							wrapper:{
								ds:{
									predefined:{
										border:"c10104",
										font__d__size:"sm",
										className:"item-list bdr-1 bxs full"
									}
								}
							}
						}
					},
					header:{
						config:{
							wrapper:{
								ds:{
									predefined:{
										border:"c10104",
										font__d__size:"sb",
										className:"item-header bdr-1 bxs full"
									}
								}
							}
						}
					},
					wrapper:{
						markup:{
							element:"ul"
						},
						ds:{
							predefined:{
								radius:"6",
								border:"c10104"
							}
						}
					},
					noresults:{
						markup:{
							element:"li"
						}
					}
				}
			}
		},
		noresult:{
			markup:{
				element:"p"
			}
		}
	}
}