const json = {
    "code":"AIOOTA",
    "name":"AIO Online travel agency",
    "description":"Detailed description about AIO online travel agency",
    "address":{
        "type":"",
        "line1":"",
        "line2":"",
        "street":"",
        "city":"Faridabad",
        "pincode":121004,
        "country":{
            "code":"IN",
            "name":"India"
        },
        "state":{
            "code":"HR",
            "name":"Haryana"
        }
    }
}

const merchantDetails = {
    "collection":{
        "name":"MerchantDetails"
    },
    "schema":{
        "code":{
            "type":"stringKey",
            "configs":{
                "aioconfig":{},
                "mongodb":{
                    "trim":true,
                    "unique":true,
                    "lowercase":true,
                    "immutable":true,
                    "required":{
                        "value":true,
                        "enable":true,
                        "message":"This field is required"
                    }
                }
            }
        },
        "name":{
            "type":"paragraph",
            "configs":{
                "aioconfig":{},
                "mongodb":{
                    "trim":true,
                    "required":{
                        "value":true,
                        "enable":true,
                        "message":"This field is required"
                    }
                }
            }
        },
        "description":{
            "type":"paragraph",
            "configs":{
                "aioconfig":{},
                "mongodb":{
                    "trim":true,
                    "required":{
                        "value":true,
                        "enable":true,
                        "message":"This field is required"
                    },
                    "minLength":{
                        "value":"10",
                        "enable":true,
                        "message":"Min length is not valid"
                    },
                    "maxLength":{
                        "value":"100",
                        "enable":true,
                        "message":"Max length is not valid"
                    }
                }
            }
        },
        "address":{
            "type":"nested",
            "schema":{
                "type":{
                    "type":"string",
                    "configs":{
                        "aioconfig":{},
                        "mongodb":{
                            "trim":true
                        }
                    }
                },
                "line1":{
                    "type":"string",
                    "configs":{
                        "aioconfig":{},
                        "mongodb":{
                            "trim":true
                        }
                    }
                },
                "line2":{
                    "type":"string",
                    "configs":{
                        "aioconfig":{},
                        "mongodb":{
                            "trim":true
                        }
                    }
                },
                "street":{
                    "type":"string",
                    "configs":{
                        "aioconfig":{},
                        "mongodb":{
                            "trim":true
                        }
                    }
                },
                "city":{
                    "type":"string",
                    "configs":{
                        "aioconfig":{},
                        "mongodb":{
                            "trim":true
                        }
                    }
                },
                "pincode":{
                    "type":"number",
                    "configs":{
                        "aioconfig":{},
                        "mongodb":{}
                    }
                },
                "country":{
                    "type":"nested",
                    "schema":{
                        "code":{
                            "type":"stringKey",
                            "configs":{
                                "aioconfig":{},
                                "mongodb":{
                                    "trim":true,
                                    "uppercase":true,
                                    "minLength":{
                                        "value":2,
                                        "enable":true,
                                        "message":"Min length is not valid"
                                    },
                                    "maxLength":{
                                        "value":"4",
                                        "enable":true,
                                        "message":"Max length is not valid"
                                    }
                                }
                            }
                        },
                        "name":{
                            "type":"string",
                            "configs":{
                                "aioconfig":{},
                                "mongodb":{
                                    "trim":true
                                }
                            }
                        }
                    }
                },
                "state":{
                    "type":"nested",
                    "schema":{
                        "code":{
                            "type":"stringKey",
                            "configs":{
                                "aioconfig":{},
                                "mongodb":{
                                    "trim":true,
                                    "uppercase":true,
                                    "minLength":{
                                        "value":2,
                                        "enable":true,
                                        "message":"Min length is not valid"
                                    },
                                    "maxLength":{
                                        "value":"4",
                                        "enable":true,
                                        "message":"Max length is not valid"
                                    }
                                }
                            }
                        },
                        "name":{
                            "type":"string",
                            "configs":{
                                "aioconfig":{},
                                "mongodb":{
                                    "trim":true
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

module.exports = merchantDetails;