const defaultConfigs = {
    common:{
        appEnv:'',
        appName:'',
        inspectAt:21,
        appInfo:{
            description:'',
            version:'0.0.1',
            author:'aio-foundation',
        },
        appConfig:{
            applicationType:'',
            appExposedIn:{
                public:false,
                partner:false,
                internal:false,
                scheduler:false
            },
            instances:{
                public:1,
                partner:1,
                internal:1,
                scheduler:1
            },
            ports:{
                public:'',
                partner:'',
                internal:'',
                scheduler:''
            }
        }
    },
    ui:{
        appConfig:{
            alias:{},
            entries:{},
            appWebCacheTime:"5d",
        },
        scssConfig:{
            hasTheme:false,
            hasDesignSystem:false,
            additionalData:{
                //"$sandeep":"kundu"
            },
            additionalDataMap:{
                //$fontsCdnPath:"appConfig.fontsCdnPath",
                //$pathPrefix:"appConfig.pathPrefix",
                //$imagesCdnPath:"appConfig.imagesCdnPath",
                //$assetsCdnPath:"appConfig.assetsCdnPath"
            }
        },
    },
    api:{
        "appConfig":{
            "dbConfigs":{
                "defaultCollections":{
                    "merchant":false,
                    "apiSchema":false,
                    "collections":false,
                    "appDetails":false
                }
            }
        },
    }
}

module.exports = defaultConfigs;