module.exports = {
    text:{
        dvalue:'',
        type:'string',
        description:"Default text",
    },

    offsets:{
        dvalue:[],
        type:'any',
        description:"Default text",
    },

    highlight:{
        type:'predefined',
        description:"",
        ___:{
            predefined:{
                from:'statics',
                mapping:'ds.configs',
                overwirte:{
                    markup:null,
                    content:null,
                    tooltip:null,
                    ds:{
                        ___:{
                            nested:{
                                predefined:{
                                    ___:{
                                        predefined:{
                                            overwirte:{
                                                color:{
                                                    dvalue:'c00000'
                                                },
                                                background:{
                                                    dvalue:'c00206'
                                                }
                                            }
                                        }
                                    }
                                },
                                css:{
                                    ___:{
                                        nested:{
                                            class:{
                                                ___:{
                                                    nested:{
                                                        family:{
                                                            dvalue:'sb'
                                                        },
                                                        padding:{
                                                            ___:{
                                                                nested:{
                                                                    1:{
                                                                        dvalue:0
                                                                    },
                                                                    2:{
                                                                        dvalue:4
                                                                    }
                                                                }
                                                            }
                                                        },
                                                        radius:{
                                                            ___:{
                                                                nested:{
                                                                    1:{
                                                                        dvalue:2
                                                                    },
                                                                    2:{
                                                                        dvalue:2
                                                                    }
                                                                }
                                                            }
                                                        },
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    wrapper:{
        type:'nested',
        description:"Default text",
        ___:{
            nested:{
                enabled:{
                    type:"boolean",
                    dvalue:false,
                },
                ds:{
                    type:'predefined',
                    description:"",
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                content:null,
                                markup:{
                                    type:'nested',
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'span'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}