module.exports = {
    "response":{
        "exclude":{
            "enable":true,
            "kies":{
                "ts":true
            }
        },
        "transform":{
            "enable":true,
            "kies":{
                "_id":"id",
                "hashId":"hId",
            }
        }
    },

    "query":{
        "runtime":{
            "enable":true,
            "configs":{
                "query":{
                    "0":{
                        "cloumn":"parentId",
                        "value":{
                            "from":"appConfig",
                            "map":"runtimeUtils.merchantRootHash",
                        },
                        "operation":{
                            "eq":{
                                "enable":true,
                                "opType":"eq"
                            }
                        }
                    }
                }
            }
        }
    },

    "signature":{
        "merge":{
            "enable":true
        },
        "creation":{
            "enable":true,
            "nodes":{
                "_id":{
                    "enable":true,
                    "valueType":"objectId"
                },
                "_merchantId":{
                    "enable":true,
                    "valueType":"objectId"
                }
            }
        }
    }
}