#user  nobody;
#worker_processes  1;

#error_log  /Library/Logs/nginx/error.log;

events {
    worker_connections  1024;
}

#access_log  /var/log/nginx/access.$year-$month-$day.log  apm_json;

http {
    include mime.types;
    default_type  application/octet-stream;

    proxy_cache_path /Users/sandy/Documents/LIB/Tools/nginx/myc levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;

    log_format  main  '$remote_addr - $remote_user kundu $time_iso8601 [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" "$http_header"';


    map $time_iso8601 $year {
        default '0000';
        "~^(\d{4})-(\d{2})-(\d{2})" $1;
    }
    map $time_iso8601 $month {
        default '00';
        "~^(\d{4})-(\d{2})-(\d{2})" $2;
    }
    map $time_iso8601 $day {
        default '00';
        "~^(\d{4})-(\d{2})-(\d{2})" $3;
    }

    error_log  /Users/sandy/Documents/LIB/Tools/nginx/error_kdkdk.log;
    access_log  /Users/sandy/Documents/LIB/Tools/nginx/access.$year-$month-$day.log  main;

    sendfile on;
    keepalive_timeout 65;

    index index.html index.php;
    root /Users/sandy/Documents/LIB/Tools/nginx/html;

    include /Users/sandy/Documents/LIB/Tools/nginx/upstream/*.conf;
    #include /Users/sandy/Documents/LIB/Tools/nginx/conf.d/*.conf;
    include /Users/sandy/Documents/LIB/Tools/nginx/sites-enabled/*.conf;
}