const schema = {
    "name":true,
    "hashId":true,
    "exposed":false,
    "roleHash":true,
    "presetHash":true,
    "roleHashMap":true,
    "nameHashId":true,
    "description":true,
    "roleAndPresetHash":true,
    "isAccessControlled":true,
}

const update = () => {
    return {...schema, ...{hashId:false}}
}

module.exports = {
    response:{
        exclude:{
            enable:true,
            kies:{
                ts:true,
                exposed:true,
                nameHashId:true,
                roleAndPresetHash:true
            }
        },
        transform:{
            enable:true,
            kies:{
                _id:"id"
            }
        }
    },
    valuemap: {
        rootParentId:{
            valuemap: {
                map:"runtimeUtils.merchantRootHash",
                from:"appConfig"
            }
        }
    },

    md5Hash:{
        nameHashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"presetHash",
                    from:"body-item"
                },
                2:{
                    map:"name",
                    from:"body-item"
                }
            }
        },
        roleAndPresetHash:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"presetHash",
                    from:"body-item"
                },
                2:{
                    map:"roleHash",
                    from:"body-item"
                }
            }
        },
        itemHashId:{
            nodes:{
                0:{
                    map:"runtimeUtils.merchantRootHash",
                    from:"appConfig"
                },
                1:{
                    map:"presetHash",
                    from:"body-item"
                },
                2:{
                    map:"number",
                    from:"random"
                }
            }
        }
    },

    schema:schema,
    schemaByType:{
        update:update()
    },

    signature:{
        merge:{
            enable:true
        },
        creation:{
            enable:true,
            nodes:{
                _id:{
                    enable:true,
                    valueType:"objectId"
                },
                _merchantId:{
                    enable:true,
                    valueType:"objectId"
                }
            }
        }
    },

    query:{
        byId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"_id",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        byPresetHash:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"presetHash",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
        hashId:{
            runtime:{
                enable:true,
                configs:{
                    query:{
                        0:{
                            cloumn:"hashId",
                            value:{
                                map:"id",
                                from:"params"
                            },
                            operation:{
                                eq:{
                                    enable:true,
                                    opType:"eq"
                                }
                            }
                        }
                    }
                }
            }
        },
    },

    validation:{
        errors:{
            nameHashId:{
                mapTo:'name',
                messages:{
                    11000:'Duplicate'
                }
            },
            roleAndPresetHash:{
                mapTo:'roleHashMap',
                messages:{
                    11000:'Duplicate'
                }
            }
        }
    }
}