module.exports = {
    config:{
        type:'predefined',
        description:"The configuration supports design system–driven customization across various elements, including the avatar image, wrapper, and initials. Properties such as size, shape, border, background color, and typography can be configured through the design system, ensuring visual consistency, accessibility, and alignment with application design standards across different themes and use cases.",
        ___:{
            predefined:{
                from:'statics',
                mapping:'ds.configs',
                overwirte:{
                    markup:{
                        ___:{
                            nested:{
                                element:{
                                    dvalue:'div'
                                }
                            }
                        }
                    },
                    ds:{
                        ___:{
                            nested:{
                                predefined:{
                                    ___:{
                                        predefined:{
                                            overwirte:{
                                                color:{
                                                    dvalue:'c00000'
                                                },
                                                minHeight:{
                                                    dvalue:1
                                                },
                                                background:{
                                                    dvalue:'c11407'
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}