const helpers = process.uiHelpers();
const badge = process.aioAppConfigs('storybook/raw/atoms/badge');

module.exports = helpers.json.merge(helpers.json.get(badge, 'props', {}), {
    avatars:{
        ___:{
            nested:{
                right:{
                    ___:{
                        asroot:false,
                        compProps:{
                            overwirte:{
                                enable:{
                                    dvalue:false
                                }
                            }
                        }
                    }
                },
                left:{
                    ___:{
                        compProps:{
                            overwirte:{
                                enable:{
                                    dvalue:false
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    icons:{
        ___:{
            nested:{
                left:{
                    ___:{
                        compProps:{
                            overwirte:{
                                config:{
                                    ___:{
                                        predefined:{
                                            overwirte:{
                                                svg:{
                                                    ___:{
                                                        nested:{
                                                            size:{
                                                                dvalue:'16px',
                                                            }
                                                        }
                                                    }
                                                },
                                                icon:{
                                                    ___:{
                                                        nested:{
                                                            size:{
                                                                dvalue:16,
                                                            },
                                                            name:{
                                                                dvalue:''
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                right:{
                    ___:{
                        compProps:{
                            overwirte:{
                                config:{
                                    ___:{
                                        predefined:{
                                            overwirte:{
                                                svg:{
                                                    ___:{
                                                        nested:{
                                                            size:{
                                                                dvalue:'16px',
                                                            }
                                                        }
                                                    }
                                                },
                                                icon:{
                                                    ___:{
                                                        nested:{
                                                            size:{
                                                                dvalue:16,
                                                            },
                                                            name:{
                                                                dvalue:''
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    config:{
        ___:{
            nested:{
                content:{
                    ___:{
                        predefined:{
                            overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            predefined:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            color:{},
                                                            background:{}
                                                        }
                                                    }
                                                }
                                            },
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    margin:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:0
                                                                                },
                                                                                2:{
                                                                                    dvalue:4
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                wrapper:{
                    ___:{
                        predefined:{
                            overwirte:{
                                ds:{
                                    ___:{
                                        nested:{
                                            predefined:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            size:{
                                                                dvalue:'lg'
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
});