const helpers = process.uiHelpers();
const itemProps = require('./../item/props');
const headerProps = require('./../header/props');

const id = helpers.random.id(10);
const rn = helpers.random.number();
const rId = `r${id}${rn}`;

const itemMapping = {
    type:"nested",
    ___:{
        nested:{
            end:{
                type:'any',
                dvalue:''
            },
            after:{
                type:'any',
                dvalue:''
            },
            start:{
                type:'any',
                dvalue:''
            },
            before:{
                type:'any',
                dvalue:''
            },
            center:{
                type:'any',
                dvalue:'label'
            }
        }
    }
}

const dvalues = () => {
    return {
        type:"nested",
        ___:{
            nested:{
                end:{
                    type:'any',
                    dvalue:rId
                },
                after:{
                    type:'any',
                    dvalue:rId
                },
                start:{
                    type:'any',
                    dvalue:rId
                },
                before:{
                    type:'any',
                    dvalue:rId
                },
                center:{
                    type:'any',
                    dvalue:rId
                }
            }
        }
    }
}

module.exports = {
    data:{
        dvalue:{},
        type:"object",
        description:"A mapping object where each property key is a number (or numeric string) and each property value is a node object. Example : <code>data = {1:{id: 1, label: 'Node 1' },2: {id: 2, label: 'Node 2' },3: {id: 3, label: 'Node 3' }}</code>"
    },
    defaults:{
        type:"nested",
        description:"A default value is the value that is automatically assigned to a variable, property, parameter, or field when no explicit value is provided to props.",
        ___:{
            nested:{
                values:{
                    type:'any',
                    dvalue:rId
                },
                childs:{
                    type:"nested",
                    description:"",
                    ___:{
                        nested:{
                            item:dvalues(),
                            header:dvalues(),
                        }
                    }
                }
            }
        }
    },
    templates:{
        type:'nested',
        description:"Collection of render functions used to customize the rendering of different sections of the component.<br/><b>header:</b> Renders custom content for the header section.<br /><b>item:</b> Renders custom content for each item. <br><b>noResults:</b> Renders custom content when no items are available to display.<br/>",
        ___:{
            nested:{
                item:{
                    type:'function',
                    description:"",
                },
                header:{
                    type:'function',
                    description:"",
                },
                noresults:{
                    type:'function',
                    description:"",
                }
            }
        }
    },
    mapping:{
        type:"nested",
        description:"Configuration object used to map display values between nodes. It specifies the source key or node that each child node should use to derive and render its display value. This enables dynamic value propagation and display across related nodes.",
        ___:{
            nested:{
                item:itemMapping,
                header:itemMapping,
                keys:{
                    type:'nested',
                    ___:{
                        nested:{
                            type:{
                                type:'string',
                                dvalue:'type'
                            }
                        }
                    }
                }
            }
        }
    },
    callbacks:{
        type:'nested',
        description:"A callback function is a function passed from a parent component to a child component through props, allowing the child component to execute logic in the parent when a specific event occurs.",
        ___:{
            nested:{
                item:itemProps.callbacks,
                header:headerProps.callbacks,
            }
        }  
    },
    config:{
        type:"nested",
        description:"The configuration supports design system–driven customization across various elements, including the item, header, wrapper and noresults. Properties such as size, shape, border, background color, and typography can be configured through the design system, ensuring visual consistency, accessibility, and alignment with application design standards across different themes and use cases.",
        ___:{
            nested:{
                item:{
                    type:"nested",
                    ___:{
                        nested:{...helpers.json.merge(itemProps, {
                            callbacks:null,
                            config:{
                                ___:{
                                    nested:{
                                        wrapper:{
                                            ___:{
                                                predefined:{
                                                    overwirte:{
                                                        markup:{
                                                            ___:{
                                                                nested:{
                                                                    element:{
                                                                        dvalue:'li'
                                                                    }
                                                                }
                                                            }
                                                        },
                                                        ds:{
                                                            ___:{
                                                                nested:{
                                                                    predefined:{
                                                                        ___:{
                                                                            predefined:{
                                                                                overwirte:{
                                                                                    border:{
                                                                                        dvalue:'c10104'
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    },
                                                                    css:{
                                                                        ___:{
                                                                            nested:{
                                                                                class:{
                                                                                    ___:{
                                                                                        nested:{
                                                                                            padding:{
                                                                                                ___:{
                                                                                                    nested:{
                                                                                                        1:{
                                                                                                            dvalue:12
                                                                                                        }, 
                                                                                                        2:{
                                                                                                            dvalue:12
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        })}
                    }
                },
                header:{
                    type:"nested",
                    ___:{
                        nested:{...helpers.json.merge(headerProps, {
                            callbacks:null,
                            config:{
                                ___:{
                                    nested:{
                                        wrapper:{
                                            ___:{
                                                predefined:{
                                                    overwirte:{
                                                        markup:{
                                                            ___:{
                                                                nested:{
                                                                    element:{
                                                                        dvalue:'li'
                                                                    }
                                                                }
                                                            }
                                                        },
                                                        ds:{
                                                            ___:{
                                                                nested:{
                                                                    predefined:{
                                                                        ___:{
                                                                            predefined:{
                                                                                overwirte:{
                                                                                    border:{
                                                                                        dvalue:'c10104'
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    },
                                                                    css:{
                                                                        ___:{
                                                                            nested:{
                                                                                class:{
                                                                                    ___:{
                                                                                        nested:{
                                                                                            padding:{
                                                                                                ___:{
                                                                                                    nested:{
                                                                                                        1:{
                                                                                                            dvalue:12
                                                                                                        }, 
                                                                                                        2:{
                                                                                                            dvalue:12
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        })}
                    }
                },
                wrapper:{
                    type:'predefined',
                    description:"A wrapper is a parent/container element that holds and manages a group of related elements, such as a list, for layout, styling, or functionality purposes.",
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                content:null,
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'ul'
                                            }
                                        }
                                    }
                                },
                                ds:{
                                    ___:{
                                        nested:{
                                            predefined:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            radius:{
                                                                dvalue:'6'
                                                            },
                                                            border:{
                                                                dvalue:'c10104'
                                                            }
                                                        }
                                                    }
                                                }
                                            },
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    borderNone:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{},
                                                                                2:{},
                                                                                3:{
                                                                                    dvalues:true
                                                                                },
                                                                                4:{}
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                noresults:{
                    type:'predefined',
                    description:"Default button",
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                content:null,
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'li'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
};