import Box from 'aio-global-raw-ui/atoms/list/box';

export default {
	title:"Atoms/List/Box",
	argTypes:{

	},
	component:Box,
	tags:['autodocs'],
	parameters:{
		layout:"centered",
		docs:{
			description:{
				component:"ContentRow is a reusable layout component that divides content into five distinct sections: start, before, center, after, and end. Parent components can pass dynamic child elements as props, which are rendered in their respective sections. This flexible structure enables developers to customize the layout while maintaining consistency across the application, making the component highly reusable for a variety of UI scenarios.<br/><br/><strong>Import path:</strong><code>import Box from 'aio-global-raw-ui/atoms/list/box';</code><br/><br/><strong>Component directory:</strong><code>./libs/frontend/ui/raw/atoms/list/box/index</code><br/><br/>"
			}
		}
	},
	mockdata:{
		defaults:{
			config:{

			},
			data:{
				0:{
					type:"item",
					label:"Item one",
					rprops:{

					}
				},
				1:{
					type:"item",
					label:"Item one",
					rprops:{

					}
				},
				2:{
					rprops:{

					},
					type:"header",
					label:"Item one",
					childs:{
						0:{
							type:"item",
							label:"Item one"
						},
						1:{
							type:"item",
							label:"Item one"
						},
						2:{
							type:"item",
							label:"Item one"
						},
						3:{
							type:"item",
							label:"Item one"
						}
					}
				}
			}
		},
		variants:{

		}
	}
}

export const Base = {
	args:{
		data:{
			0:{
				type:"item",
				label:"Item one",
				rprops:{

				}
			},
			1:{
				type:"item",
				label:"Item one",
				rprops:{

				}
			},
			2:{
				rprops:{

				},
				type:"header",
				label:"Item one",
				childs:{
					0:{
						type:"item",
						label:"Item one"
					},
					1:{
						type:"item",
						label:"Item one"
					},
					2:{
						type:"item",
						label:"Item one"
					},
					3:{
						type:"item",
						label:"Item one"
					}
				}
			}
		},
		defaults:{
			values:"r6qtCIYiJBO726080440970044098",
			childs:{
				item:{
					end:"r6qtCIYiJBO726080440970044098",
					after:"r6qtCIYiJBO726080440970044098",
					start:"r6qtCIYiJBO726080440970044098",
					before:"r6qtCIYiJBO726080440970044098",
					center:"r6qtCIYiJBO726080440970044098"
				},
				header:{
					end:"r6qtCIYiJBO726080440970044098",
					after:"r6qtCIYiJBO726080440970044098",
					start:"r6qtCIYiJBO726080440970044098",
					before:"r6qtCIYiJBO726080440970044098",
					center:"r6qtCIYiJBO726080440970044098"
				}
			}
		},
		mapping:{
			item:{
				end:'',
				after:'',
				start:'',
				before:'',
				center:"label"
			},
			header:{
				end:'',
				after:'',
				start:'',
				before:'',
				center:"label"
			},
			keys:{
				type:"type"
			}
		},
		callbacks:{
			item:{
				onClick:null,
				onBlur:null,
				onFocus:null,
				onKeyUp:null,
				dsTheme:null,
				onKeyDown:null,
				onDragStart:null,
				onMouseDown:null,
				onPointerUp:null,
				onPointerDown:null,
				onPointerEnter:null,
				onPointerLeave:null,
				beforeRender:null
			},
			header:{
				onClick:null,
				onBlur:null,
				onFocus:null,
				onKeyUp:null,
				dsTheme:null,
				onKeyDown:null,
				onDragStart:null,
				onMouseDown:null,
				onPointerUp:null,
				onPointerDown:null,
				onPointerEnter:null,
				onPointerLeave:null,
				beforeRender:null
			}
		},
		config:{
			item:{
				childs:{
					start:'',
					before:'',
					center:'',
					end:'',
					after:''
				},
				config:{
					center:{
						markup:{
							element:"div"
						}
					},
					wrapper:{
						markup:{
							element:"li"
						},
						ds:{
							predefined:{
								border:"c10104",
								font__d__size:"sm",
								className:"item-list bdr-1 bxs full"
							},
							css:{
								class:{
									borderNone:{
										1:true,
										2:true,
										3:false,
										4:true
									},
									padding:{
										1:12,
										2:12
									}
								}
							}
						}
					},
					end:{
						markup:{
							element:"div"
						},
						ds:{
							css:{
								class:{
									padding:{
										1:0,
										2:0,
										3:0,
										4:8
									}
								}
							}
						}
					},
					after:{
						markup:{
							element:"div"
						},
						ds:{
							css:{
								class:{
									padding:{
										1:0,
										2:0,
										3:0,
										4:8
									}
								}
							}
						}
					},
					start:{
						markup:{
							element:"div"
						},
						ds:{
							css:{
								class:{
									padding:{
										1:0,
										2:8,
										3:0,
										4:0
									}
								}
							}
						}
					},
					before:{
						markup:{
							element:"div"
						},
						ds:{
							css:{
								class:{
									padding:{
										1:0,
										2:8,
										3:0,
										4:0
									}
								}
							}
						}
					}
				}
			},
			header:{
				childs:{
					start:'',
					before:'',
					center:'',
					end:'',
					after:''
				},
				config:{
					center:{
						markup:{
							element:"div"
						}
					},
					wrapper:{
						markup:{
							element:"li"
						},
						ds:{
							predefined:{
								border:"c10104",
								font__d__size:"sb",
								className:"item-header bdr-1 bxs full"
							},
							css:{
								class:{
									borderNone:{
										1:true,
										2:true,
										3:false,
										4:true
									},
									padding:{
										1:12,
										2:12
									}
								}
							}
						}
					},
					end:{
						markup:{
							element:"div"
						},
						ds:{
							css:{
								class:{
									padding:{
										1:0,
										2:0,
										3:0,
										4:8
									}
								}
							}
						}
					},
					after:{
						markup:{
							element:"div"
						},
						ds:{
							css:{
								class:{
									padding:{
										1:0,
										2:0,
										3:0,
										4:8
									}
								}
							}
						}
					},
					start:{
						markup:{
							element:"div"
						},
						ds:{
							css:{
								class:{
									padding:{
										1:0,
										2:8,
										3:0,
										4:0
									}
								}
							}
						}
					},
					before:{
						markup:{
							element:"div"
						},
						ds:{
							css:{
								class:{
									padding:{
										1:0,
										2:8,
										3:0,
										4:0
									}
								}
							}
						}
					}
				}
			},
			wrapper:{
				markup:{
					element:"ul"
				},
				ds:{
					predefined:{
						radius:"6",
						border:"c10104"
					}
				}
			},
			noresults:{
				markup:{
					element:"li"
				}
			}
		}
	}
}