module.exports = {
    "schema":{
        "appId":true,
        "type":true,
    },

    "valuemap":{
        "appId":{
            "valuemap":{
                "map":"id",
                "from":"params"
            }
        },
        "type":{
            "valuemap":{
                "map":"subId",
                "from":"params"
            }
        }
    },

    "signature":{
        "creation":{
            "enable":true,
            "nodes":{
                "_id":{
                    "enable":true,
                    "valueType":"objectId"
                },
                "_mapId":{
                    "enable":true,
                    "valueType":"objectId"
                },
                "_merchantId":{
                    "enable":true,
                    "valueType":"objectId"
                }
            }
        }
    },

    "query":{
        "runtime":{
            "enable":true,
            "configs":{
                "logical":{
                    "and":{
                        "query":{
                            "0":{
                                "cloumn":"appId",
                                "value":{
                                    "from":"params",
                                    "map":"id"
                                },
                                "operation":{
                                    "eq":{
                                        "enable":true,
                                        "opType":"eq"
                                    }
                                }
                            },
                            "1":{
                                "cloumn":"type",
                                "value":{
                                    "from":"params",
                                    "map":"subId"
                                },
                                "operation":{
                                    "eq":{
                                        "enable":true,
                                        "opType":"eq"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}