import helpers from 'ui-helpers';
import Badge from 'aio-global-ui/atoms/badge';
import Icon from 'aio-global-ui/atoms/icon';
import React, { useEffect, useState } from 'react';

const comp = (props) => {

    const themes = helpers.json.val(props, 'themes', []);
    const colorPairs = helpers.json.val(props, 'colorPairs', []);

    const ds = () => {

    }

    const list = (th) => {
        return (
            <>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="sm"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    'isDisplay':true
                                }
                            }
                        }}
                        label={th}
                        element="span"
                        avatar={<Icon />}
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="lg"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                }
                            }
                        }}
                        label={th}
                        element="span"
                        avatar={<Icon />}
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="xl"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                }
                            }
                        }}
                        label={th}
                        element="span"
                        avatar={<Icon />}
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="sm"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                        avatar={<Icon />}
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="lg"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                        avatar={<Icon />}
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="xl"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                        avatar={<Icon />}
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="sm"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="lg"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="xl"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="sm"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="lg"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="xl"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="sm"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":false,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        leftIcon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="lg"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":false,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        leftIcon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="xl"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":false,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                            }
                        }}
                        leftIcon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                        label={th}
                        element="span"
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="sm"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":false,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                                "other":'mr-r10'
                            }
                        }}
                        leftIcon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                        label={th}
                        element="span"
                    />
                    <Badge 
                        size="lg"
                        label={th}
                        element="span"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":false,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                                "other":'mr-r10'
                            }
                        }}
                        icon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                    />
                    <Badge 
                        size="xl"
                        label={th}
                        element="span"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":false,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                                "other":'mr-r10'
                            }
                        }}
                        icon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                    />
                </li>
                <li className='gird-1 mr-r4'>
                    <Badge 
                        size="sm"
                        label={th}
                        element="span"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":false,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                                "other":'mr-r10'
                            }
                        }}
                        icon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                    />
                    <Badge 
                        size="lg"
                        label={th}
                        element="span"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":true,
                                    "disabled":false,
                                    "isDisplay":false
                                },
                                "other":'mr-r10'
                            }
                        }}
                        icon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                    />
                    <Badge 
                        size="xl"
                        label={th}
                        element="span"
                        ds={{
                            "theme":{
                                "colorPairing":{
                                    "default":th
                                }
                            },
                            "css":{
                                "class":{
                                    "shadow":"",
                                    "radius":{
                                        "1":4
                                    }
                                },
                                "flags":{
                                    "noBorder":false,
                                    "rounded":false,
                                    "disabled":true,
                                    "isDisplay":false
                                },
                                "other":'mr-r10'
                            }
                        }}
                        icon={{
                            "name":"da",
                            "family":"hotels",
                        }}
                    />
                </li>
            </>
        )
    }

    const ui = () => {
        if(colorPairs && colorPairs.length > 0){
            return colorPairs.map((item, index) => {
                return (
                    <ul className='full mr-t16 flx grid-wrapper' key={index}>
                        {list(item)}
                    </ul>
                )
            })
        }else{
            return <></>
        }
    }

    return <>
        <p className='dis-md mr-b10'>Badges :</p>
        {ui()}
    </>
}

export default comp;