const helpers = process.uiHelpers();
const choice = require('./../choice');

module.exports = helpers.json.merge(helpers.json.get(choice, 'props', {}), {
    mode:null,
    theme:{
        ___:{
            nested:{
                default:{
                    ___:{
                        nested:{
                            checkbox:{
                                ___:{
                                    nested:{
                                        predefined:{
                                            ___:{
                                                predefined:{
                                                    overwirte:{
                                                        background:{
                                                            dvalue:'c00102'
                                                        },
                                                        bbackground:{
                                                            dvalue:'c00000'
                                                        },
                                                        border:{
                                                            dvalue:'c00102'
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    checkbox:{
        type:"nested",
        ___:{
            nested:{
                ds:{
                    ___:{
                        predefined:{
                            overwirte:{

                                //c00102
                                ds:{
                                    ___:{
                                        nested:{
                                            css:{
                                                ___:{
                                                    nested:{
                                                        flags:{
                                                            ___:{
                                                                nested:{
                                                                    rounded:{
                                                                        dvalue:true
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    holder:{
        ___:{
            compProps:{
                overwirte:{
                    layer:{
                        ___:{
                            nested:{
                                size:{
                                    dvalue:36
                                }
                            }
                        }
                    }
                }
            }
        }
    },
})