const schema = {
    "appId":{
        "type":"objectId",
        "configs":{
            "mongodb":{
                "required":{
                    "value":true,
                    "enable":true,
                    "message":"This field is required"
                },
                "immutable":true
            }
        }
    },

    "type":{
        "type":"stringKey",
        "configs":{
            "mongodb":{
                "trim":true,
                "required":{
                    "value":true,
                    "enable":true,
                    "message":"This field is required"
                },
                "lowercase":true
            }
        }
    },

    "name":{
        "type":"stringKey",
        "configs":{
            "mongodb":{
                "trim":true,
                "required":{
                    "value":true,
                    "enable":true,
                    "message":"This field is required"
                }
            }
        }
    },

    "hashId":{
        "type":"stringKey",
        "configs":{
            "mongodb":{
                "trim":true,
                "unique":true,
                "required":{
                    "value":true,
                    "enable":true,
                    "message":"This field is required"
                },
                "minLength":{
                    "value":"32",
                    "enable":true,
                    "message":"Min length is not valid {VALUE}"
                },
                "maxLength":{
                    "value":"32",
                    "enable":true,
                    "message":"Max length is not valid"
                },
                "immutable":true
            }
        }
    },
    "parentId":{
        "type":"stringKey",
        "configs":{
            "aioconfig":{},
            "mongodb":{
                "trim":true,
                "required":{
                    "value":true,
                    "enable":true,
                    "message":"This field is required"
                },
                "minLength":{
                    "value":"32",
                    "enable":true,
                    "message":"Min length is not valid"
                },
                "maxLength":{
                    "value":"32",
                    "enable":true,
                    "message":"Max length is not valid"
                },
                "immutable":true
            }
        }
    },
    "model":{
        "type":"nested",
        "schema":{
            "response":{
                "type":"nested",
                "schema":{
                    "exclude":{
                        "type":"nested",
                        "schema":{
                            "enable":{
                                "type":"boolean",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":false
                                        }
                                    }
                                }
                            },
                            "kies":{
                                "type":"object",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":{}
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "schemaSample":{
                "type":"object",
                "configs":{
                    "aioconfig":{},
                    "mongodb":{
                        "default":{
                            "value":{}
                        }
                    }
                }
            },
            "valuemap":{
                "type":"object",
                "configs":{
                    "aioconfig":{},
                    "mongodb":{
                        "default":{
                            "value":{}
                        }
                    }
                }
            },
            "pagination":{
                "type":"nested",
                "schema":{
                    "enable":{
                        "type":"boolean",
                        "configs":{
                            "aioconfig":{},
                            "mongodb":{
                                "default":{
                                    "value":false
                                }
                            }
                        }
                    },
                    "limit":{
                        "type":"nested",
                        "schema":{
                            "min":{
                                "type":"number",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":"1"
                                        }
                                    }
                                }
                            },
                            "max":{
                                "type":"number",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":"10"
                                        }
                                    }
                                }
                            },
                            "default":{
                                "type":"number",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":"5"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "signature":{
                "type":"nested",
                "schema":{
                    "merge":{
                        "type":"nested",
                        "schema":{
                            "enable":{
                                "type":"boolean",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":false
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "creation":{
                        "type":"nested",
                        "schema":{
                            "enable":{
                                "type":"boolean",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":false
                                        }
                                    }
                                }
                            },
                            "nodes":{
                                "type":"object",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":{}
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "query":{
                "type":"nested",
                "schema":{
                    "hidden":{
                        "type":"nested",
                        "schema":{
                            "enable":{
                                "type":"boolean",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":false
                                        }
                                    }
                                }
                            },
                            "columns":{
                                "type":"object",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":{}
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "runtime":{
                        "type":"nested",
                        "schema":{
                            "enable":{
                                "type":"boolean",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":false
                                        }
                                    }
                                }
                            },
                            "configs":{
                                "type":"object",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":{}
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "validation":{
        "type":"nested",
        "schema":{
            "request":{
                "type":"nested",
                "schema":{
                    "auth":{
                        "type":"nested",
                        "schema":{}
                    },
                    "body":{
                        "type":"nested",
                        "schema":{
                            "min":{
                                "type":"number",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":"1"
                                        }
                                    }
                                }
                            },
                            "max":{
                                "type":"number",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "default":{
                                            "value":"10"
                                        }
                                    }
                                }
                            },
                            "type":{
                                "type":"stringKey",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "trim":true,
                                        "default":{
                                            "value":"object"
                                        },
                                        "lowercase":true
                                    }
                                }
                            },
                            "required":{
                                "type":"stringKey",
                                "configs":{
                                    "aioconfig":{},
                                    "mongodb":{
                                        "trim":true,
                                        "default":{
                                            "value":"optional"
                                        },
                                        "lowercase":true
                                    }
                                }
                            },
                            "message":{
                                "type":"nested",
                                "schema":{
                                    "error":{
                                        "type":"string",
                                        "configs":{
                                            "aioconfig":{},
                                            "mongodb":{
                                                "trim":true,
                                                "default":{
                                                    "value":"Invalid body data"
                                                }
                                            }
                                        }
                                    },
                                    "success":{
                                        "type":"string",
                                        "configs":{
                                            "aioconfig":{},
                                            "mongodb":{
                                                "trim":true,
                                                "default":{
                                                    "value":"Valid body data"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "methods":{
                        "type":"nested",
                        "schema":{
                            "get":{
                                "type":"nested",
                                "schema":{
                                    "allowed":{
                                        "type":"boolean",
                                        "configs":{
                                            "aioconfig":{},
                                            "mongodb":{
                                                "default":{
                                                    "value":false
                                                }
                                            }
                                        }
                                    },
                                    "message":{
                                        "type":"nested",
                                        "schema":{
                                            "error":{
                                                "type":"string",
                                                "configs":{
                                                    "aioconfig":{},
                                                    "mongodb":{
                                                        "trim":true,
                                                        "default":{
                                                            "value":"Get method is not allowed"
                                                        }
                                                    }
                                                }
                                            },
                                            "success":{
                                                "type":"string",
                                                "configs":{
                                                    "aioconfig":{},
                                                    "mongodb":{
                                                        "trim":true,
                                                        "default":{
                                                            "value":"Get method is allowed"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            "post":{
                                "type":"nested",
                                "schema":{
                                    "allowed":{
                                        "type":"boolean",
                                        "configs":{
                                            "aioconfig":{},
                                            "mongodb":{
                                                "default":{
                                                    "value":false
                                                }
                                            }
                                        }
                                    },
                                    "message":{
                                        "type":"nested",
                                        "schema":{
                                            "error":{
                                                "type":"string",
                                                "configs":{
                                                    "aioconfig":{},
                                                    "mongodb":{
                                                        "trim":true,
                                                        "default":{
                                                            "value":"Post method is not allowed"
                                                        }
                                                    }
                                                }
                                            },
                                            "success":{
                                                "type":"string",
                                                "configs":{
                                                    "aioconfig":{},
                                                    "mongodb":{
                                                        "trim":true,
                                                        "default":{
                                                            "value":"Post method is allowed"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            "put":{
                                "type":"nested",
                                "schema":{
                                    "allowed":{
                                        "type":"boolean",
                                        "configs":{
                                            "aioconfig":{},
                                            "mongodb":{
                                                "default":{
                                                    "value":false
                                                }
                                            }
                                        }
                                    },
                                    "message":{
                                        "type":"nested",
                                        "schema":{
                                            "error":{
                                                "type":"string",
                                                "configs":{
                                                    "aioconfig":{},
                                                    "mongodb":{
                                                        "trim":true,
                                                        "default":{
                                                            "value":"Put method is not allowed"
                                                        }
                                                    }
                                                }
                                            },
                                            "success":{
                                                "type":"string",
                                                "configs":{
                                                    "aioconfig":{},
                                                    "mongodb":{
                                                        "trim":true,
                                                        "default":{
                                                            "value":"Put method is allowed"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            "delete":{
                                "type":"nested",
                                "schema":{
                                    "allowed":{
                                        "type":"boolean",
                                        "configs":{
                                            "aioconfig":{},
                                            "mongodb":{
                                                "default":{
                                                    "value":false
                                                }
                                            }
                                        }
                                    },
                                    "message":{
                                        "type":"nested",
                                        "schema":{
                                            "error":{
                                                "type":"string",
                                                "configs":{
                                                    "aioconfig":{},
                                                    "mongodb":{
                                                        "trim":true,
                                                        "default":{
                                                            "value":"Delete method is not allowed"
                                                        }
                                                    }
                                                }
                                            },
                                            "success":{
                                                "type":"string",
                                                "configs":{
                                                    "aioconfig":{},
                                                    "mongodb":{
                                                        "trim":true,
                                                        "default":{
                                                            "value":"Delete method is allowed"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "headers":{
                        "type":"nested",
                        "schema":{}
                    }
                }
            },
            "validation":{
                "type":"nested",
                "schema":{
                    "body":{
                        "type":"object",
                        "configs":{
                            "aioconfig":{},
                            "mongodb":{
                                "default":{
                                    "value":{}
                                }
                            }
                        }
                    },
                    "query":{
                        "type":"object",
                        "configs":{
                            "aioconfig":{},
                            "mongodb":{
                                "default":{
                                    "value":{}
                                }
                            }
                        }
                    },
                    "params":{
                        "type":"object",
                        "configs":{
                            "aioconfig":{},
                            "mongodb":{
                                "default":{
                                    "value":{}
                                }
                            }
                        }
                    },
                    "headers":{
                        "type":"object",
                        "configs":{
                            "aioconfig":{},
                            "mongodb":{
                                "default":{
                                    "value":{}
                                }
                            }
                        }
                    },
                    "cookies":{
                        "type":"object",
                        "configs":{
                            "aioconfig":{},
                            "mongodb":{
                                "default":{
                                    "value":{}
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

const t = {
    "collection":{
        "name":"apiSchema"
    },
    "schema":schema
}

module.exports = t