const helpers = process.uiHelpers();
const icon = process.aioAppConfigs('storybook/raw/atoms/icons');
const row = process.aioAppConfigs('storybook/raw/atoms/content-row');
const storybook = {
    predefined:process.aioAppConfigs('storybook/predefined')
}

module.exports = helpers.json.merge(helpers.json.get(row, 'props', {}), {
    expendIcon:{
        type:'nested',
        description:'',
        ___:{
            nested:{
                exclude:{
                    dvalue:false,
                    type:'boolean'
                },
                show:{
                    dvalue:true,
                    type:'boolean'
                },
                state:{
                    type:"enum",
                    dvalue:'default',
                    description:"",
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:"tree.row.states"
                        }
                    }
                },
                placement:{
                    type:"enum",
                    dvalue:'start',
                    description:"",
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:"content.row.childs"
                        }
                    }
                },
                names:{
                    type:'nested',
                    ___:{
                        nested:{
                            selected:{
                                type:'string',
                                dvalue:'arrow-down'
                            },
                            default:{
                                type:'string',
                                dvalue:'arrow-right'
                            }
                        }
                    }
                },
                config:{
                    type:'nested',
                    ___:{
                        nested:helpers.json.merge(helpers.json.get(icon, 'props', {}), {
                            config:{
                                ___:{
                                    predefined:{
                                        overwirte:{
                                            svg:{
                                                ___:{
                                                    nested:{
                                                        size:{
                                                            dvalue:'20px'
                                                        }
                                                    }
                                                }
                                            },
                                            icon:{
                                                ___:{
                                                    nested:{
                                                        size:{
                                                            dvalue:'20'
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        })
                    }
                }
            }
        }
    },
    config:{
        ___:{
            nested:{
                start:{
                    ___:{
                        predefined:{
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{}
                                        }
                                    }
                                },
                                ds:{
                                    ___:{
                                        nested:{
                                            predefined:{
                                                ___:{
                                                    predefined:{
                                                        overwirte:{
                                                            color:{},
                                                            background:{}
                                                        }
                                                    }
                                                }
                                            },
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    margin:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:0
                                                                                },
                                                                                2:{
                                                                                    dvalue:8
                                                                                },
                                                                                3:{
                                                                                    dvalue:0
                                                                                },
                                                                                4:{
                                                                                    dvalue:0
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                wrapper:{
                    ___:{
                        predefined:{
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{}
                                        }
                                    }
                                },
                                ds:{
                                    ___:{
                                        nested:{
                                            css:{
                                                ___:{
                                                    nested:{
                                                        class:{
                                                            ___:{
                                                                nested:{
                                                                    cursor:{
                                                                        dvalue:'cp'
                                                                    },
                                                                    fontsize:{
                                                                        dvalue:'sm'
                                                                    },
                                                                    padding:{
                                                                        ___:{
                                                                            nested:{
                                                                                1:{
                                                                                    dvalue:8
                                                                                },
                                                                                2:{
                                                                                    dvalue:12
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
});