const helpers = process.uiHelpers();
const contentRow = require('./../../content-row/props');

module.exports = helpers.json.merge(contentRow, {
    config:{
    ___:{
        nested:{
            wrapper:{
                ___:{
                    predefined:{
                        overwirte:{
                            markup:{
                                ___:{
                                    nested:{
                                        element:{
                                            dvalue:'li'
                                        }
                                    }
                                }
                            },
                            ds:{
                                ___:{
                                    nested:{
                                        predefined:{
                                            ___:{
                                                predefined:{
                                                    overwirte:{
                                                        font__d__size:{
                                                            dvalue:'sm'
                                                        },
                                                        className:{
                                                            dvalue:'item-list bdr-1 bxs full'
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        css:{
                                            ___:{
                                                nested:{
                                                    class:{
                                                        ___:{
                                                            nested:{
                                                                borderNone:{
                                                                    ___:{
                                                                        nested:{
                                                                            1:{
                                                                                dvalue:true
                                                                            },
                                                                            2:{
                                                                                dvalue:true
                                                                            },
                                                                            3:{
                                                                                dvalue:false
                                                                            },
                                                                            4:{
                                                                                dvalue:true
                                                                            }
                                                                        }
                                                                    }
                                                                },
                                                                padding:{
                                                                    ___:{
                                                                        nested:{
                                                                            1:{
                                                                                dvalue:8
                                                                            },
                                                                            2:{
                                                                                dvalue:8
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            start:{
                ___:{
                    predefined:{
                        overwirte:{
                            ds:{
                                ___:{
                                    nested:{
                                        css:{
                                            ___:{
                                                nested:{
                                                    class:{
                                                        ___:{
                                                            nested:{
                                                                padding:{
                                                                    ___:{
                                                                        nested:{
                                                                            1:{
                                                                                dvalue:0
                                                                            },
                                                                            2:{
                                                                                dvalue:8
                                                                            },
                                                                            3:{
                                                                                dvalue:0
                                                                            },
                                                                            4:{
                                                                                dvalue:0
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            before:{
                ___:{
                    predefined:{
                        overwirte:{
                            ds:{
                                ___:{
                                    nested:{
                                        css:{
                                            ___:{
                                                nested:{
                                                    class:{
                                                        ___:{
                                                            nested:{
                                                                padding:{
                                                                    ___:{
                                                                        nested:{
                                                                            1:{
                                                                                dvalue:0
                                                                            },
                                                                            2:{
                                                                                dvalue:8
                                                                            },
                                                                            3:{
                                                                                dvalue:0
                                                                            },
                                                                            4:{
                                                                                dvalue:0
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            after:{
                ___:{
                    predefined:{
                        overwirte:{
                            ds:{
                                ___:{
                                    nested:{
                                        css:{
                                            ___:{
                                                nested:{
                                                    class:{
                                                        ___:{
                                                            nested:{
                                                                padding:{
                                                                    ___:{
                                                                        nested:{
                                                                            1:{
                                                                                dvalue:0
                                                                            },
                                                                            2:{
                                                                                dvalue:0
                                                                            },
                                                                            3:{
                                                                                dvalue:0
                                                                            },
                                                                            4:{
                                                                                dvalue:8
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            end:{
                ___:{
                    predefined:{
                        overwirte:{
                            ds:{
                                ___:{
                                    nested:{
                                        css:{
                                            ___:{
                                                nested:{
                                                    class:{
                                                        ___:{
                                                            nested:{
                                                                padding:{
                                                                    ___:{
                                                                        nested:{
                                                                            1:{
                                                                                dvalue:0
                                                                            },
                                                                            2:{
                                                                                dvalue:0
                                                                            },
                                                                            3:{
                                                                                dvalue:0
                                                                            },
                                                                            4:{
                                                                                dvalue:8
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}});