module.exports = {
    config:{
        type:'compProps',
        description:"Contains the configuration-to-props mapping for the component. Values defined here are transformed into component props and applied when the component is rendered.",
        ___:{
            asroot:true,
            compProps:{
                from:'statics',
                mapping:'raw/atoms/typography/heading',
                overwirte:{
                    config:{
                        ___:{
                            predefined:{
                                overwirte:{
                                    markup:{
                                        ___:{
                                            nested:{
                                                element:{
                                                    dvalue:'h3'
                                                }
                                            }
                                        }
                                    },
                                    ds:{
                                        ___:{
                                            nested:{
                                                css:{
                                                    ___:{
                                                        nested:{
                                                            class:{
                                                                ___:{
                                                                    nested:{
                                                                        fontsize:{
                                                                            dvalue:'lg',
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    } 
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}