module.exports = {
    templates:{
        description:"Collection of render functions used to customize the rendering of different sections of the component. <br/><b>trigger:</b> Renders custom content for the trigger section <br/><b>content:</b> Renders custom content for the content section.",
        type:"nested",
        ___:{
            nested:{
                trigger:{
                    type:'any'
                },
                content:{
                    type:'any'
                }
            }
        }
    },
    controls:{
        type:'nested',
        description:"Configuration object used to define and customize interactive controls for component properties.",
        ___:{
            nested:{
                open:{
                    dvalue:false,
                    type:"boolean",
                    description:""
                },
                arrow:{
                    dvalue:true,
                    type:"boolean",
                    description:""
                },
                mode:{
                    type:"enum",
                    dvalue:'static',
                    description:"",
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:"popover.modes"
                        }
                    }
                },
                toggle:{
                    type:"enum",
                    dvalue:'click',
                    description:"",
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:"popover.toggle"
                        }
                    }
                },
                position:{
                    type:"enum",
                    dvalue:'bottom-right',
                    description:"",
                    ___:{
                        enum:{
                            from:'statics',
                            mapping:"popover.position"
                        }
                    }
                }
            }
        }
    },
    config:{
        type:'nested',
        description:"The configuration supports design system–driven customization across various elements, including the wrapper, container, content and layer. Properties such as size, shape, border, background color, and typography can be configured through the design system, ensuring visual consistency, accessibility, and alignment with application design standards across different themes and use cases.",
        ___:{
            nested:{
                wrapper:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                container:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                content:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                layer:{
                    description:"",
                    type:'predefined',
                    ___:{
                        predefined:{
                            from:'statics',
                            mapping:'ds.configs',
                            overwirte:{
                                markup:{
                                    ___:{
                                        nested:{
                                            element:{
                                                dvalue:'div'
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}